### ISSUE TITLE
Install on Linux Deploy doesn't work

### ISSUE THREAD

**Issue by adikpb** [DesktopECHO/Pi-hole-for-Android#1]
After pressing on install, this is the only thing thats shown:
```
[hh:mm:ss] >>> deploy
[hh:mm:ss] <<< deploy
```

**Comment by PauloFreire70** [comment]
Hello @adikpb please review all the settings and make sure you're following the instructions, it should work although I did not tried the latest version. 
@DesktopECHO I wonder how can one update the existing installation without losing the existing settings and data? I've tried the native pi-hole method but gives some errors. Thank you and have a great 2022!

**Comment by adikpb** [comment]
@PauloFreire70 I have followed all the instruction. But I do wonder if may source path is okay: 
`Internal storage/Download/p4a14.tar.gz`

**Comment by PauloFreire70** [comment]
@adikpb try /storage/emulated/0/Download/p4a14.tar.gz (it's also case sensitive)

**Comment by adikpb** [comment]
Still the same sadly...

**Comment by DesktopECHO** [comment]
Hi, have you tried installing the SELinux mode changer APK I linked to in the readme?  Can you confirm device is rooted?

**Comment by adikpb** [comment]
The device is indeed rooted (using magisk), and SELinux Switch is installed. I think i may have found the problem, the selinux state is not changed despite clicking on the button in  selinux switch.

**Comment by DesktopECHO** [comment]
SELinux will need a reboot

**Comment by DesktopECHO** [comment]
Sorry I closed this accidentally yesterday...
Question - What is your device's make/model?  I have had some difficulty with certain devices but have never run into a situation where a new Kernel is needed.

@PauloFreire70  - "_pihole -up_" should work ok with the **p4a14.tar.gz** release.  If it doesn't please open a new issue.

**Comment by adikpb** [comment]
The devices is an Samsung Galaxy Tab 2 (SM-T19) running nougat(android 7), stock rom and kernel. I also tried installing busybox and using selinux switch but it made no difference...

**Comment by DesktopECHO** [comment]
If you want to be sure about the file path location, I suggest downloading InShot File Manager from the Play Store.  Open it and browse to p4a14.tar.gz, then touch **...More** and **Properties** -- It will show the absolute path.  Click **Copy Path** and paste that directly into Linux Deploy.  This way you can be 100% sure the location is correct.

Regarding your Tablet, you sure it's not SM-T**8**19?

It looks like Samsung developed a hardening layer for Android called Knox, and it's on most of their devices.  I've seen reports of this causing trouble in Linux Deploy - [Possible workarounds](https://forum.xda-developers.com/t/rom-unofficial-10-lineageos-17-1-t713-t719-t813-t819.4070161/)

I think the easiest way to deal with this is to install LineageOS [(XDA Link)](https://forum.xda-developers.com/t/rom-unofficial-10-lineageos-17-1-t713-t719-t813-t819.4070161/) on the tablet and call it a day.  Shouldn't have any problems installing an LD  image from LineageOS as Knox is removed.

**Comment by adikpb** [comment]
Hey, sorry for the late reply and the typo the device is indeed the SM-T819. I have confirmed the file path using InShot file manager. It seems that the link for `Possible workarounds` and `(XDA Link)` seems to be the same, is this intentional?

**Comment by adikpb** [comment]
Oops, closed it accidentally

**Comment by adikpb** [comment]
Got LineageOS flashed, rooted the device, and have se linux set to permissive. The install went fine without a hitch but when the container is started it show rc.local fail. Not able to connect to it as well..

**Comment by DesktopECHO** [comment]
Can you send a screenshot of your deployment?  I've attached a screenshot from a Moto G7 for comparison

In this example the deployment finished at 14:55:58.  I started the instance at 14:56:24 and Linux Deploy said everything was ready in 12 seconds.

![Screenshot_20211230-145654_Linux_Deploy](https://user-images.githubusercontent.com/33142753/147781893-5513e555-e609-4927-9b79-40bf75a49a01.png)

**Comment by DesktopECHO** [comment]
FYI - I fixed the link you asked about earlier:  Linux Deploy - [Possible workarounds for Knox](https://github.com/meefik/linuxdeploy/issues/224)

In any case, LineageOS was a much better option.
None of the devices I've tried ever showed an error starting the instance in the way you describe, I'm curious what the difference may be...

**Comment by adikpb** [comment]
Heres the screenshot:
![Screenshot_20211230-235923_Linux_Deploy](https://user-images.githubusercontent.com/67222969/147784454-37fa2bf3-56ff-4248-96f0-14e48eb7a0d2.png)

**Comment by DesktopECHO** [comment]
Can you try changing the init system to **sysv** from _run-parts_ and do another screenshot?  I expect changing the init system will break other things, but it may help troubleshooting.

**Comment by adikpb** [comment]
Here you go:
![Screenshot_20211231-001320_Linux_Deploy](https://user-images.githubusercontent.com/67222969/147785297-db129777-558e-4dc6-9a83-770dcde42642.png)

**Comment by DesktopECHO** [comment]
Looks like it may have something to do with an encrypted filesystem.  Can you try re-deploying to a new destination? 

Try this as an install location: ``/data/data/ru.meefik.linuxdeploy/files/p4a.img`` 
(...or wherever **/ru.meefik.linuxdeploy/files** is located on your device)

**Comment by adikpb** [comment]
Changed the installation path to /data/data/ru.meefik.linuxdeploy/files/p4a.img and its still the same...

**Comment by adikpb** [comment]
I turned on both debug mode and trace mode from debug mode in settings, hope it helps!!
[Screenshot_20211231-085110_Linux_Deploy](https://user-images.githubusercontent.com/67222969/147804039-cd92c2a5-734b-4ce4-b713-20c10a91b787.png)
![Screenshot_20211231-085045_Linux_Deploy](https://user-images.githubusercontent.com/67222969/147804032-6e1c7c8e-b87c-435d-b6c9-3eb79444e489.png)

**Comment by DesktopECHO** [comment]
It looks like here is where the wheels fell off...

![image](https://user-images.githubusercontent.com/33142753/147830964-c024bfce-30de-4b1d-a02e-6b27c89aa5ac.png)

...but not seeing any other clues.


Can you enable Telnet in Linux Deploy and try to access it from there?

```
[zero@macpro ~]$ telnet 10.73.0.112 5023
Trying 10.73.0.112...
Connected to 10.73.0.112.
Escape character is '^]'.

Linux Deploy aarch64 /dev/pts/0
$ su -c "linuxdeploy shell -u root"
:: Configuring core/mnt ... 
:: Configuring core/net ... 
CentOS Linux 7 (AltArch) [running via Linux Deploy]
Last login: Fri Dec 31 11:50:43 AST 2021
```
Then try to run /etc/rc.local
```
[root@localhost ~]# /etc/rc.local
Preparing...                          ################################# [100%]
Updating / installing...
   1:unbound-libs-1.14.0-1.el7        ################################# [ 50%]
   2:unbound-1.14.0-1.el7             ################################# [100%]
24
Starting syslog-ng:                                        [  OK  ]
Starting crond:                                            [  OK  ]
Starting generate the dss key:                             [  OK  ]
Starting generate the rsa key:                             [  OK  ]
Starting dropbear:                                         [  OK  ]

Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to /etc/xrdp/rsakeys.ini

Generating a 2048 bit RSA private key
.................................+++
.................................................................................................+++
writing new private key to 'key.pem'
-----
Starting xrdp: daemon process 9423 started ok
                                                           [  OK  ]
Starting lighttpd:                                         [  OK  ]
Starting unbound:                                          [  OK  ]
Not running

FTL started!

[root@localhost ~]# 

```

**Comment by DesktopECHO** [comment]
Another thing to try -- Instead of installing to a disk image, try installing to a directory instead.  Set a destination like:

```/data/user/0/ru.meefik.linuxdeploy/bin/linuxdeploy/files/p4a```

**Comment by DesktopECHO** [comment]
One more idea:  Try LineageOS 16 from XDA, perhaps there's an issue with this specific ROM.

**Comment by adikpb** [comment]
This is what i get when i try telnet:
 ```
~ % telnet 192.168.68.110 5023
Trying 192.168.68.110...
Connected to 192.168.68.110.
Escape character is '^]'.

Linux Deploy aarch64 /dev/pts/0
$ su -c "linuxdeploy shell -u root"
:: Configuring core/mnt ...
:: Configuring core/net ...
CentOS Linux 7 (AltArch) [running via Linux Deploy]
Segmentation fault```

**Comment by adikpb** [comment]
The same happens when I install it as a file instead of an image.

**Comment by adikpb** [comment]
I will try LineagoeOS 16 later... Anyways, HAPPY NEW YEAR!!

**Comment by DesktopECHO** [comment]
Thank you, happy new year!  
Let us know how things go with LineageOS 16 - It's very strange the instance won't even start-up, let alone start the services.

**Comment by adikpb** [comment]
Seems that i cant flash LineageOs 16. Oh well, thanks for your time anyways.

**Comment by DesktopECHO** [comment]
No problem, sorry to hear you didn't have any success as this is the first report a user was unable to install the image.  

There's a LineageOS 15.1 build as well you can try if you ever want to take this on again -> [XDA Forums](https://forum.xda-developers.com/t/rom-unofficial-t819-8-1-lineageos-15-1.3732070/)
