### ISSUE TITLE
Can't change any pihole settings

### ISSUE THREAD

**Issue by Evaldash** [DesktopECHO/Pi-hole-for-Android#12]
Hi, I've encountered an odd issue. I'd like to manually select the upstream DNS servers in the pihole web interface, but for some reason when change any settings, once I click save nothing changes. Any ideas why that could be? I've tested it on my pi zero, and everything seems to work fine...

Say I'd like to enable google DNS:
![image](https://user-images.githubusercontent.com/61429051/163729261-007d422b-857c-44e0-8948-d71e304001ea.png)

Once I click save, the settings return to the original values...
![image](https://user-images.githubusercontent.com/61429051/163729303-a4b86fce-ae28-485d-8a4b-b9f7300d0fe2.png)

**Comment by DesktopECHO** [comment]
Hi There,

It’s because the Pi-hole image includes Unbound DNS-over-TLS and it’s enabled by default.

Have a look at the upstream DNS server settings on the right (127.0.0.1#5335) Uncheck that first then you’ll be able to save your own DNS server (but you’re better off with Unbound+DoT, imho)

**Comment by Evaldash** [comment]
Tried that, same thing happens, once I click save no settings are saved.

**Comment by DesktopECHO** [comment]
That’s strange.  I will try to reproduce the issue when I have some free cycles.  In the meantime if you’re comfortable in the terminal you can try setting the DNS servers in /etc/Pi-hole/setupVars.conf

**Comment by DesktopECHO** [comment]
Hi, I could not replicate this issue on multiple ARMv7 and ARMv8 Android devices... closing.
