### ISSUE TITLE
Installing PiVPN with this Pihole Install

### ISSUE THREAD

**Issue by ambitiousnuisance** [DesktopECHO/Pi-hole-for-Android#16]
I am curious if its possible to install Pivpn with this my Pihole for android installation and run them both at the same time

**Comment by DesktopECHO** [comment]
Maybe not PiVPN exactly, but I'm sure some sort of VPN server could be made to work.
In a pinch, OpenSSH ```-D``` SOCKS5 proxy server to the rescue.

**Comment by DesktopECHO** [comment]
https://dltj.org/article/ssh-as-socks-proxy/
