### ISSUE TITLE
Update to Realtime clock solution

### ISSUE THREAD

**Issue by hqnicolas** [DesktopECHO/Pi-hole-for-Android#21]
i tested this project with a TVbox android,
when i lock the entire network DNS via Pi-hole 
After power loss
The Clock servers wont connect before the pi-hole start to work, thanks to unbound.
so Unbound returns SERVFAIL for all queries because time error 

to recovery from that i need to 
`sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"`

i think the DNS encripted protocol can't run without realtime device....
How we can inprove that, for non Realtime battery Devices?
can we patch it?

**Comment by DesktopECHO** [comment]
Hi, yes this can be fixed - I will include ntp in the next release.
In the meantime, you can add the fix you suggested to /etc/rc.local and it will run when the instance is started.
(I suggest maybe using `1.1.1.1` if DNS isn't available, and `/etc/rc.local` runs as `root` so no need to `sudo`)

`date -s "$(wget -qSO- --max-redirect=0 1.1.1.1 2>&1 | grep Date: | cut -d' ' -f5-8)Z"`
