### ISSUE TITLE
Support for i386

### ISSUE THREAD

**Issue by GoldenFroze** [DesktopECHO/Pi-hole-for-Android#23]
Unfortunately I only have zenfone 5 t00j phone, which has intel atom as soc. Could u support it by any chance?

![image](https://user-images.githubusercontent.com/28603849/194833165-544a0e94-d521-4c27-ada0-d083b53ea578.png)

**Comment by hqnicolas** [comment]
[It can be used on any rooted Android device with an ARMv7 or newer CPU](https://github.com/DesktopECHO/Pi-hole-for-Android#readme)
[Clovertrail ](https://liliputing.com/intel-atom-clover-trail-chips-designed-for-windows-8-not-linux/)is [an X86 Like Desktop CPU](https://en.wikipedia.org/wiki/Atom_(system_on_a_chip))

**Comment by DesktopECHO** [comment]
Sorry I won't be able to assist.  I'd need an Intel-based handset to get this done and the number of them out there is tiny compared with ARM.
