### ISSUE TITLE
whats the password for microsoft remote desktop?

### ISSUE THREAD

**Issue by hanswurst31** [DesktopECHO/Pi-hole-for-Android#25]
thx................

**Comment by DesktopECHO** [comment]
Whatever password you set in Linux Deploy per the instructions @ https://github.com/DesktopECHO/Pi-hole-for-Android

**Comment by hanswurst31** [comment]
If its the following part:

"Set password for user android"

I set both username and password to just one letter but upon clicking on ok the window just closes. 2nd try the windows just closes again. On the 3rd try i get the errror that login failed for user android.
![20221024_080413](https://user-images.githubusercontent.com/31671744/197459187-b3b99edb-94ac-4476-b020-8fdf579e24b8.jpg)
![Uploading 20221024_080846.jpg…]()

**Comment by hanswurst31** [comment]
After this abtryed the username"android" and a more complex password but getting the same result.
![20221024_080846](https://user-images.githubusercontent.com/31671744/197459444-ed40a01d-494e-402e-ac37-520caad24497.jpg)

**Comment by DesktopECHO** [comment]
Are you able to login via SSH?  
I'm seeing an RDP issue on Android 12 devices as well.  What version is your device running?

**Comment by nar3n12** [comment]
> Are you able to login via SSH? I'm seeing an RDP issue on Android 12 devices as well. What version is your device running?

Hey, I'm facing the same issue. As you mentioned, it is possible to login through SSH but not via RDP.
Device: Samsung Z flip 3
Android 13
