### ISSUE TITLE
Unable to access admin console after installing

### ISSUE THREAD

**Issue by DkGnjCfEcA** [DesktopECHO/Pi-hole-for-Android#3]
Hi,
I have successfully installed this on a MotoZ2 force running lineage 18.1, and everything seems fine except I can't access the admin console. I can do SSH and RDP access.

Please see the screenshots:
![Screenshot_20220114-140348_Trebuchet](https://user-images.githubusercontent.com/93782948/149571287-f6fd6620-127f-4bfe-8f7a-86286523b136.png)
![Screenshot 2022-01-14 140828](https://user-images.githubusercontent.com/93782948/149571506-875cdb9e-d251-47a2-9111-76ed07e6001c.png)

**Comment by DesktopECHO** [comment]
What's the output of ``service lighttpd status``

**Comment by DkGnjCfEcA** [comment]
It shows as stopped.

[android@localhost ~]$ service lighttpd status
lighttpd is stopped...

**Comment by DesktopECHO** [comment]
I was a little too fast on the send button there... 

If it's showing ``lighttpd is stopped...`` You can try to start the web server manually with:

``service lighttpd start``

**Comment by DkGnjCfEcA** [comment]
That is also failing. I tried stopping and starting the container with same results:

[android@localhost ~]$ service lighttpd start
Starting lighttpd: 2022-01-14 14:23:11: (network.c.307) can't bind to socket: 0.0.0.0:80 Address already in use
                                                           [FAILED]

**Comment by DkGnjCfEcA** [comment]
You mean the base android OS or the container? Here is the output of the command:
[android@localhost ~]$ sudo lsof -i :80
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
libwebser 10115 root    3u  IPv4  73682      0t0  TCP localhost:http (LISTEN)
[android@localhost ~]$

**Comment by DkGnjCfEcA** [comment]
That did the trick. Going to test this out now :-) Thanks.

**Comment by DesktopECHO** [comment]
So ``libwebser`` is the culprit.  Not sure what that does, and no clues on google.

I don't think we fixed anything at this point.  Easist thing to do is change the Pi-hole web server port from 80 to something not being used.  Try this:

``sed -i 's/= 80/= 60080/g'  /etc/lighttpd/lighttpd.conf ; service lighttpd restart``

If that works then you can reach the admin page at ``http://[YOUR_IP]:60080``

**Comment by DkGnjCfEcA** [comment]
quick question, but unrelated, there is a setting to keep the screen on, is that necessary considering that we are running it on a phone?

**Comment by DesktopECHO** [comment]
You can try disabling that option and see what happens.
Try to bring up the web page a few minutes/hours later to see if your device is still responding.  
Worst case scenario, if you need the screen on all the time just set your screen brightness to its lowest setting.

**Comment by DesktopECHO** [comment]
If you do need to have the screen on all the time, I usually install the Microsoft RDP client on the device and have it login to localhost.  Then you can run ``padd`` so you get real-time Pi-hole stats displayed right on your phone.  There are other methods to do this if you know your way around Android but RDP'ing into localhost is easy for folks new to Pi-hole or Android.

Many RaspberryPi users running Pi-hole buy screens for their devices just to accomplish what's already built into a repurposed phone!

**Comment by DkGnjCfEcA** [comment]
That's a good suggestion to use the screen. For now it seems to be running fine with screen off. 
Running pihole is really good use of those old phone lying in the drawers.

**Comment by youngt2** [comment]
I had this same issue. Setting a different port in `/etc/lighttpd/lighttpd.conf` solved it for me. Seems lineageos was using port 80 for something?

**Comment by shufuwa** [comment]
> You mean the base android OS or the container? I might have something running on the android, so going to try disabling most of the user apps and see if that helps.
> 
> Here is the output of the command: [android@localhost ~]$ sudo lsof -i :80 COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME libwebser 10115 root 3u IPv4 73682 0t0 TCP localhost:http (LISTEN) [android@localhost ~]$

could it be that you had adaway or some adblocker with root access running before this ?

**Comment by ow3rk1ll** [comment]
> sed -i 's/= 80/= 60080/g' /etc/lighttpd/lighttpd.conf ; service lighttpd restart

hello i am having exact same error when ones i try this its gives me permission denied error
