### ISSUE TITLE
Getting this error while installing :  WARNING: linker: Unsupported flags DT_FLAGS_1=0x8000001

### ISSUE THREAD

**Issue by MrVKY** [DesktopECHO/Pi-hole-for-Android#31]
I tried hitting install with Pi Deploy app and Im getting the same error over and over again. Then I tried installing raspbian using Linux deploy from play store and it got installed without any error. Any idea why?

**Comment by DesktopECHO** [comment]
Hi there, what model is your device and what version of Android are you running?
Is is possible to send me a screenshot for more context?  I've not seen this error before.

**Comment by DesktopECHO** [comment]
Also - Just to confirm, is this just a warning or does Pi Deploy break when you see this warning?

**Comment by DesktopECHO** [comment]
Did you use Magisk to root your physical device?
If so, updating to Magisk 25.2 may help -- https://github.com/topjohnwu/Magisk/issues/5589

Still investigating the cause here and how it can be dealt with...  Something to do with using a newer NDK than the one used for the original Linux Deploy.

Good to hear at least the image works on Linux Deploy, but I'd like to sort this out so new users have an easy method for instalation.  Thanks for your report.

**Comment by MrVKY** [comment]
No. I used custom recovery (twrp) to root my physical device. 
I'm not sure about my android emulator root method (it has custom recovery by default I guess)

**Comment by DesktopECHO** [comment]
Hi please give the latest release another try.  I made some fixes to support Android 5.x so those linker warnings don't come up anymore.

**Comment by MrVKY** [comment]
Hey! I tried the latest apk. The linker warnings are gone but I'm getting a mounting error while installing. 
![Screenshot_2022-10-31-14-18-51](https://user-images.githubusercontent.com/62804612/199030008-46729a22-62fc-45c3-b216-c223a599583f.png)

**Comment by DesktopECHO** [comment]
Did this continue after power-cycling the device?

**Comment by MrVKY** [comment]
Yes! It does

**Comment by DesktopECHO** [comment]
That's a loop device so something else is mounting it. 
Remove any copies of Linux Deploy and Pi Deploy already present, Reboot the Phone, reinstall pideploy.apk. 
Open Pi Deploy...  Hit install.
You should a toast notification from Magisk or SuperSU that root is being used.

**Comment by DesktopECHO** [comment]
Also... disable auto-start in Settings so we don't have that possibly interfering.

**Comment by MrVKY** [comment]
It didn't help. Still getting the same mount fail error.
Also I forgot to mention something else, when I launch piDeploy I get an error saying **pkill: not found** . (before even hitting install)
![Screenshot_2022-10-31-16-06-26](https://user-images.githubusercontent.com/62804612/199055067-6e00d600-57f7-4f2c-89e6-7c871402343b.png)

**Comment by DesktopECHO** [comment]
You running SuperSU?  I've seen the same thing specific to a RK3288 device running Lollypop.  The root manager is not letting Pi Deploy continue.

Can you see if Pi-Deploy is in the list of allowed apps in your root app, and (for SuperSU Free anyway) uncheck 'show notifications' to see Toast Notifications.

If you fire up the app and don't get the initial grant request from your root manager, there will be issues.

**Comment by MrVKY** [comment]
Yes I'm running SuperSU. The toast isn't showing up when I open the application. But When I hit install, I get the toast.

**Comment by DesktopECHO** [comment]
There's an option in SuperSU to 'Install to /System' - Can you run that and reboot?   Then uninstall/reinstall the APK

**Comment by MrVKY** [comment]
The 'Install SuperSU into /System' is saying, SuperSU is already a system app.
![Screenshot_2022-10-31-17-02-44](https://user-images.githubusercontent.com/62804612/199066080-38dbe14d-e6b0-4498-b9d9-b15cee26ea73.png)

**Comment by DesktopECHO** [comment]
Ok, in the Apps tab, do you see Pi Deploy?

**Comment by MrVKY** [comment]
Yes
![Screenshot_2022-10-31-17-05-39](https://user-images.githubusercontent.com/62804612/199066832-78b4e56a-6a91-4652-9a60-b6090ff6e3b9.png)

**Comment by MrVKY** [comment]
Deleted the file. 
Force closed and reopened the app. Still getting the same mounting error!!

**Comment by DesktopECHO** [comment]
Can you remove the folder `/data/local/raspbian` and try again?

**Comment by MrVKY** [comment]
Noob question. You mean 'internal storage/android/data' ? If yes, there's no raspbian folder in data.

**Comment by DesktopECHO** [comment]
Actually /data/local/raspbian... you may need a root file-explorer or ADB to get to that path

**Comment by MrVKY** [comment]
Deleted '/data/local/raspbian'  
Still no luck!

**Comment by DesktopECHO** [comment]
Reboot the device and try again.  If there's no raspbian folder there's nothing to cause an error, which is impossible!

**Comment by MrVKY** [comment]
Deleted the folder, Rebooted the device. The raspbian folder is not there, Launched piDeploy, getting the same error!!!

**Comment by MrVKY** [comment]
But after getting that error, I checked the data folder. The raspbian folder was there, Deleted that folder and tried multiple times. Still getting that error.

**Comment by DesktopECHO** [comment]
Close Pi Deploy 
In SuperSU, remove Pi Deploy from allowed apps
Open Pi-Deploy, lets see if it asks for permissions again.

**Comment by DesktopECHO** [comment]
One other thing to try after that. 
Change **Installation Type** from `File` to `Directory` and **Installation Path** to `/data/local/rpi`

**Comment by MrVKY** [comment]
Heyyyy!!
Changed the installation, it showed some error but installed successfully. Pihole installed successfully and its working fine!!!

**Comment by DesktopECHO** [comment]
Great!
Can you do me a favour?  

Stop/Start the instance 
- Login via RDP to test functionality
- Login via SSH as well 
- Login to Pi-hole Web interface

If you can do all of the above I think you're good to go!

**Comment by MrVKY** [comment]
Yeah, I can do all you've listed perfectly! Thanks for your help :)
