### ISSUE TITLE
Getting the error : pideploy: /data/user/0/com.desktopecho.pideploy/files/cli.sh: line 1068: mkdir: Permission denied

### ISSUE THREAD

**Issue by N0ub4x** [DesktopECHO/Pi-hole-for-Android#32]
Hello, I was installing Pi-Hole for Android on my Samsung Galaxy S8 with Magisk and i get this error :
`pideploy: /data/user/0/com.desktopecho.pideploy/files/cli.sh: line 1068: mkdir: Permission denied` while installing.

I activate the Storage Access.
I restart the Application.
I restart my Phone and i still get this error.

What should i do ?

![Screenshot_20221101-141830_Pi Deploy](https://user-images.githubusercontent.com/85786075/199244066-67ae5634-7e8d-4aae-a31b-60854edad8d0.jpg)

**Comment by DesktopECHO** [comment]
Hi can you tap "three vertical dots on top right" and tap "Status"

What does it say regarding **Selinux**?

**Comment by N0ub4x** [comment]
![20221101_154917](https://user-images.githubusercontent.com/85786075/199262524-c8400528-a207-4874-b2b6-2175691e579c.jpg)

**Comment by DesktopECHO** [comment]
Grab the the latest [Busybox](https://github.com/meefik/busybox/releases/) APK.  

Install Busybox in /system/xbin. 

Open Settings (three dashes at top left)
In Properties menu: 
 - Set _**PATH variable**_ to `/system/xbin` 
 - Tap _**Update ENV**_

Then tap "Stop" - 
Try to Install again.

**Comment by N0ub4x** [comment]
I can't install Busybox.
![20221101_160719](https://user-images.githubusercontent.com/85786075/199266577-2e3648ad-4fd2-4b15-a3e6-598055ab64e0.jpg)

**Comment by N0ub4x** [comment]
I still get the error on Busybox.

**Comment by DesktopECHO** [comment]
No idea what's wrong at this point.   

What ROM are you running?  

If it's stock, [Knox ](https://en.wikipedia.org/wiki/Samsung_Knox)on Samsung ROMs can be troublesome.  There's been a few Samsung owners on the GitHub issues page with similar reports. Always looks permissions related with access denied messages everywhere.  These issues go away with flashing LineageOS (Up to 18.1) or a "DeKnoxed" ROM on XDA.

**Comment by DesktopECHO** [comment]
Excellent!  Thanks for the update, it may help others who run into this issue.
