### ISSUE TITLE
Error: Kernel Too Old

### ISSUE THREAD

**Issue by nikhilk0** [DesktopECHO/Pi-hole-for-Android#33]
Today, I tried out the newer PiDeploy version on my Super Old Xperia U (Cm12.1) got the below errors.

While Installation:
![Screenshot_2022-11-05-10-56-38](https://user-images.githubusercontent.com/45728234/200104813-8795e43c-d339-4015-a065-fe5c412a0d70.png)

When I Clicked on Start after Installation was complete (got the above error during installation but still showed deployment is completed)
![Screenshot_2022-11-05-10-56-48](https://user-images.githubusercontent.com/45728234/200104938-2873cb95-bbef-41b3-ac27-b3112490b127.png)

Here's my Kernel Version for reference:
![Screenshot_2022-11-05-10-57-03](https://user-images.githubusercontent.com/45728234/200104948-9931300b-0d81-459b-84d2-503bc04631e1.png)

Before getting the above error, I got mount error but resolved it by changing Installation Type from File to Directory as suggested [here](https://github.com/DesktopECHO/Pi-hole-for-Android/issues/31#issuecomment-1297452836)

I was using the legacy version earlier on CM11, but since last 2 months FTL updates were not getting installed. So, tried this newer version.

Hope there's some workaround available for this issue.

Anyways, Thanks a ton for this project.

**Comment by DesktopECHO** [comment]
Hi there, 

With a 3.0 Kernel like the one you're running, you definitely need to use Linux Deploy and the 'legacy' disk image -- It should update to the latest version of Pi-hole just fine by running `p4a-install`  If it's doesn't let me know and I can assist.

**Comment by nikhilk0** [comment]
I have redownloaded the latest legacy image and installed it. Currently it's on the latest pihole version. So, wasn't able to recreate my earlier issue. Will let you know if I face the issue with future updates. 

Thanks again!
