### ISSUE TITLE
Errors when checking for version and FTL not updating to v5.19.2 after "p4a-install"

### ISSUE THREAD

**Issue by FDisk80** [DesktopECHO/Pi-hole-for-Android#36]
[✓] Update complete!

**/etc/pihole/versions: line 14: invalid: command not found
/etc/pihole/versions: line 15: Command:: command not found
/etc/pihole/versions: line 16: Try: command not found**
Cloning into 'FTL'...sion is v5.14.1
remote: Enumerating objects: 295, done.
remote: Counting objects: 100% (295/295), done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 295 (delta 25), reused 105 (delta 12), pack-reused 0
Receiving objects: 100% (295/295), 3.38 MiB | 104.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.

Building pihole-FTL from source.  This will take a few minutes...

**/etc/pihole/versions: line 14: invalid: command not found
/etc/pihole/versions: line 15: Command:: command not found
/etc/pihole/versions: line 16: Try: command not found**
  Pi-hole version is v5.14.1 (Latest: v5.14.1)
  AdminLTE version is v5.17 (Latest: v5.17)
  **FTL version is v5.16.3 (Latest: v5.19.2)**
  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

**Comment by FDisk80** [comment]
Should I start from scratch with the new Pi Deploy installation method? Or is it possible to fix with previous installation method?

**Comment by DesktopECHO** [comment]
Hi I'm looking into this...  Ideally if you're on Android 5.x or newer, go with the new Pi Deploy package.  

I'm not seeing your reported issue but I do have a problem compiling pihole-FTL due to a new build dependency upstream.

**Comment by DesktopECHO** [comment]
Looks like pihole-FTL v5.19 requires Nettle 3.4.1... CentOS 7 ships with 2.7-ish...

![image](https://user-images.githubusercontent.com/33142753/202921540-bc68dca6-90ae-49d8-a8d1-f0243d05044f.png)

**Comment by FDisk80** [comment]
Yea, I went with a new deploy and everything is working fine. Thanks.

**Comment by DesktopECHO** [comment]
Good to hear, thanks for the feedback.

**Comment by DesktopECHO** [comment]
For Legacy Android 4.x devices, run:

`sudo rpm -ivh https://github.com/DesktopECHO/Pi-hole-for-Android/raw/legacy/rpm/nettle-3.4.1-7.el7.armv7hl.rpm https://github.com/DesktopECHO/Pi-hole-for-Android/raw/legacy/rpm/nettle-devel-3.4.1-7.el7.armv7hl.rpm --force`

Re-run `p4a-install` and pihole-FTL will compile normally.

**Comment by nikhilk0** [comment]
Getting below error when running `p4a-install` on android 4.4

![image](https://user-images.githubusercontent.com/45728234/203097177-cff63c7d-c6e9-4c23-b854-21abc4c3fdc1.png)

I have updated Nettle as suggested above.

**Comment by DesktopECHO** [comment]
These are just (new) warnings but harmless... the build should finish successfully.

**Comment by nikhilk0** [comment]
Looks like 512mb ram isn't enough to perform this update operation. My phone got super slow while updating. I waited for about 20 mins but the ssh connection closed automatically.

Looks like the end of road for 4.x devices. I had a good run with this project on this device. But it looks like I'll need to find alternate solutions. Either a newer distro or newer device.

**Comment by DesktopECHO** [comment]
Reboot your device and start fresh.  
It may take a couple of tries but it should work.  
If your SSH connection is being dropped you can try temporarily enabling the telnet server (and disable localhost only).
Telnet in on 5023 and run `linuxdeploy shell`  
You'll be dropped into the chroot and re-try `p4a-install` from there.

**Comment by Adel0201** [comment]
Hey

I am running pihole on android 4.1

and I ran this command: sudo rpm -ivh https://github.com/DesktopECHO/Pi-hole-for-Android/raw/legacy/rpm/nettle-3.4.1-7.el7.armv7hl.rpm https://github.com/DesktopECHO/Pi-hole-for-Android/raw/legacy/rpm/nettle-devel-3.4.1-7.el7.armv7hl.rpm --force

and then "p4a-install" but i still getting errors.
