### ISSUE TITLE
Pihole problem? 

### ISSUE THREAD

**Issue by dangel1967** [DesktopECHO/Pi-hole-for-Android#38]
I just installed pihole on my phone but when I go to run it it just keeps saying it needs superuser privileges. And in terminal mode, it says it refused to connect to a certain website. Help!

**Comment by DesktopECHO** [comment]
First thing your need to do is root your device.
Visit [XDA](https://forum.xda-developers.com/) to find specific instructions on how to accomplish this.  
(The steps will vary depending on your device.)

**Comment by dangel1967** [comment]
I saw the instructions but it's a little complicated. Is there an easier way of doing it?

**Comment by DesktopECHO** [comment]
Sorry, nope -- You need a rooted device to get started.

**Comment by dangel1967** [comment]
I have it working thanks all!
