### ISSUE TITLE
Unable to resolve DNS from ssh session

### ISSUE THREAD

**Issue by wizard-28** [DesktopECHO/Pi-hole-for-Android#39]
```bash
android@j7elte:~$ ping google.com
ping: google.com: Temporary failure in name resolution
```

Here's my `/etc/resolv.conf`:

```
nameserver 8.8.8.8
```

**Comment by DesktopECHO** [comment]
Hi, can you try `ping 8.8.8.8` to verify internet connectivity, and `sudo ping google.com` to see if it's permissions related?

**Comment by wizard-28** [comment]
```
android@j7elte:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=119 time=74.8 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=119 time=79.7 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=119 time=76.7 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=119 time=83.9 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 74.843/78.802/83.900/3.417 ms
android@j7elte:~$ sudo ping google.com
ping: google.com: Temporary failure in name resolution
```

**Comment by DesktopECHO** [comment]
How about `ping one.one.one.one` or some other domain, same thing still happening?

**Comment by DesktopECHO** [comment]
Also, what does `nslookup` say?

![image](https://user-images.githubusercontent.com/33142753/205122604-55222064-0ca6-4305-9c1d-fdc134cabb7a.png)

**Comment by wizard-28** [comment]
```bash
android@j7elte:~$ ping one.one.one.one
ping: one.one.one.one: Temporary failure in name resolution
android@j7elte:~$ nslookup
> google.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	google.com
Address: 142.251.42.14
Name:	google.com
Address: 2404:6800:4009:815::200e
```

**Comment by DesktopECHO** [comment]
What kind of device do you have, stock ROM or 3rd party like LineageOS?

**Comment by wizard-28** [comment]
Looks like the DNS resolution is flaky, it works randomly.

```
android@j7elte:~$ ping google.com
PING google.com (172.217.174.78) 56(84) bytes of data.
64 bytes from bom07s25-in-f14.1e100.net (172.217.174.78): icmp_seq=1 ttl=119 time=72.6 ms
64 bytes from bom07s25-in-f14.1e100.net (172.217.174.78): icmp_seq=2 ttl=119 time=73.4 ms
64 bytes from bom07s25-in-f14.1e100.net (172.217.174.78): icmp_seq=3 ttl=119 time=72.5 ms
64 bytes from bom07s25-in-f14.1e100.net (172.217.174.78): icmp_seq=4 ttl=119 time=73.0 ms
^C
--- google.com ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 8161ms
rtt min/avg/max/mdev = 72.488/72.851/73.351/0.339 ms
android@j7elte:~$ ping github.com
PING github.com (20.207.73.82) 56(84) bytes of data.
^C
--- github.com ping statistics ---
13 packets transmitted, 0 received, 100% packet loss, time 11999ms
```

**Comment by wizard-28** [comment]
> What kind of device do you have, stock ROM or 3rd party like LineageOS?

Lineage OS 20.0 (unofficial)

**Comment by wizard-28** [comment]
```
android@j7elte:~$ cat /etc/resolv.conf
nameserver 1.1.1.1
android@j7elte:~$ ping google.com
ping: google.com: Temporary failure in name resolution
android@j7elte:~$ ping github.com
ping: github.com: Temporary failure in name resolution
android@j7elte:~$
```

**Comment by wizard-28** [comment]
> Are you behind a VPN?

No

---

> Reboot the device to see if the issue persists.

I've rebooted it many times before making this issue.

> You never mentioned the device model

SM-J700F

> do you have issues in Android-native apps?

No

**Comment by DesktopECHO** [comment]
Is Pi-hole is running?  If so try setting your DNS in `/etc/resolv.conf` to `127.0.0.1`

**Comment by DesktopECHO** [comment]
Ok!  DNS works using Pi-hole, at least you're not _completely_ dead in the water.  

I have no idea why you're having this issue with other DNS servers.  Where did you find LineageOS 20 for a Galaxy J7?

**Comment by wizard-28** [comment]
> Ok! DNS works using Pi-hole, at least you're not _completely_ dead in the water.
> 
> I have no idea why you're having this issue with other DNS servers. Where did you find LineageOS 20 for a Galaxy J7?

https://forum.xda-developers.com/t/rom-13-j7elte-j7xlte-unofficial-lineageos-20-0-alpha.4524889/

**Comment by DesktopECHO** [comment]
This ROM was released a day ago and labeled ALPHA.

I would suggest trying a ROM a more extensively tested to see if your problem persists, or lock in DNS to 127.0.0.1 and call it a day...

**Comment by wizard-28** [comment]
> lock in DNS to 127.0.0.1 and call it a day...

I guess I'll do this for now... Any way to fix the 100% packet loss thing?

**Comment by wizard-28** [comment]
```
android@j7elte:~$ ping github.com
PING github.com (20.207.73.82) 56(84) bytes of data.
^C
--- github.com ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5004ms

android@j7elte:~$ ping gitlab.com
PING gitlab.com (172.65.251.78) 56(84) bytes of data.
64 bytes from 172.65.251.78 (172.65.251.78): icmp_seq=1 ttl=49 time=89.3 ms
64 bytes from 172.65.251.78 (172.65.251.78): icmp_seq=2 ttl=49 time=92.5 ms
64 bytes from 172.65.251.78 (172.65.251.78): icmp_seq=3 ttl=49 time=157 ms
64 bytes from 172.65.251.78 (172.65.251.78): icmp_seq=4 ttl=49 time=109 ms
^C
--- gitlab.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 89.342/111.983/157.133/27.114 ms
android@j7elte:~$ ping duckduckgo.com
PING duckduckgo.com (40.81.94.43) 56(84) bytes of data.
^C
--- duckduckgo.com ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 10001ms
```

**Comment by DesktopECHO** [comment]
Yes, try an older ROM that's been out for a while and has positive feedback in the XDA forums.

**Comment by DesktopECHO** [comment]
...oh, also try giving the dev a heads-up about your issue.  He can't improve his ROM without feedback, and having Android 13 running on a 7 year old phone is a commendable accomplishment.
  
He may know something, or disagree there's a bug, either way worth a try.
