### ISSUE TITLE
PADD in Fullscreen 

### ISSUE THREAD

**Issue by Zocker1012** [DesktopECHO/Pi-hole-for-Android#4]
I am testing your pihole centOS system image since yesterday.

pihole and unbound are working perfectly.

My only problem is this:
How can i get PADD to show automatically in Fullscreen, without an titlebar or something on an rdp client on the same device?

thanks for your previous work

**Comment by DesktopECHO** [comment]
Thanks!

- Edit ``~/.config/qterminal.org/qterminal.ini``
- Set ``HideTabBarWithOneTab`` to ``true``

**Comment by Zocker1012** [comment]
Thanks!

For some reason changing the ini file manually didn't work.

I had to deselect the option  fixed tab width. Then the option  hide tab bar with only one tab  appeared in the preferences menu.

Problem solved! 

by the way, updating PADD doesn't work properly.

what is the right way to do it. or shouldn't you do that?

```
CD ~
wget -N https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh
```
is this still the right way to update it?

Greetings

**Comment by DesktopECHO** [comment]
This should do the trick:

``wget -N https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh -O /bin/padd``

**Comment by Zocker1012** [comment]
It's late here.
I didn't come up with this idea.

Thanks for the quick help.

A few minor changes in the padd file + autostart padd and everything works for now.

Unfortunately, PADD does not recognize a temperature sensor on my device.
I think this is normal because of chroot.

**Comment by DesktopECHO** [comment]
Of the handful of devices I've tried about half have working temperature sensors - I was surprised to see any of them working.
It may be possible to hack around the Pi-hole source code to point it at the correct location in ``/proc``
