### ISSUE TITLE
Unable to reconnect to the wifi network after disconnection

### ISSUE THREAD

**Issue by wizard-28** [DesktopECHO/Pi-hole-for-Android#40]
Sometimes I'm able to reconnect without issues but almost every time it says that the DNS address could not be found.

![issue](https://user-images.githubusercontent.com/49679481/205445400-91f964f0-b36f-4243-b74f-d7790bb66d37.jpg)

I then have to resort to restarting the router to reconnect successfully.

**Comment by DesktopECHO** [comment]
Open the app, tap STOP -- It will take a moment to shut down the instance.  Then tap START to restart the instance.

**Comment by DesktopECHO** [comment]
One other thing -- Make sure your install is updated as Pi-hole 5.19 (released about 3 weeks ago) had a bug that crashed FTL.

**Comment by wizard-28** [comment]
> One other thing -- Make sure your install is updated as Pi-hole 5.19 (released about 3 weeks ago) had a bug that crashed FTL.

My Pi-Hole is up-to-date.

---

> Open the app, tap STOP -- It will take a moment to shut down the instance. Then tap START to restart the instance.

Is there really no fix for this? Do I need to restart the instance every time I (re)connect a device to the wifi?

**Comment by DesktopECHO** [comment]
Can you confirm you have this entry in Local DNS?
`connectivitycheck.gstatic.com  |  142.250.80.3`

![image](https://user-images.githubusercontent.com/33142753/205710117-5f710096-1720-4a37-957e-2992ca64fbe8.png)

**Comment by wizard-28** [comment]
> Can you confirm you have this entry in Local DNS? `connectivitycheck.gstatic.com | 142.250.80.3`
> 
> ![image](https://user-images.githubusercontent.com/33142753/205710117-5f710096-1720-4a37-957e-2992ca64fbe8.png)

Yes

**Comment by DesktopECHO** [comment]
Are you connecting to the same WiFi access point every time, or switching between different ones?

**Comment by wizard-28** [comment]
> Are you connecting to the same WiFi access point every time, or switching between different ones?

I only have one wifi AP in my house. So all the devices connect to that.

**Comment by DesktopECHO** [comment]
Are you using Pi-hole on your Android device at home all the time, and is the device disconnecting from WiFi on its own?

**Comment by wizard-28** [comment]
> Are you using Pi-hole on your Android device at home all the time

No, the Pi-Hole is shut down at night.

> and is the device disconnecting from WiFi on its own?

The Pi-Hole is neither disconnecting from the WiFi, nor does it have any issues reconnecting to the WiFi.

The issues described in this issue are faced from other devices (my laptop, my mother's phone etc) when reconnecting to the WiFi, after they've been disconnected (disconnected normally when taken out of the house).

**Comment by DesktopECHO** [comment]
Ok got it, thanks for the extra info.  

When a device rejoins your network and is unable to resolve DNS, can you run `ipconfig /all` (or equivalent) to verify it's using the correct DNS server?  (that should be the IP of the Pi-hole)

If some devices continue to resolve DNS using Pi-hole, while others do not after (re)joining your WiFi, there has to be a configuration issue somewhere.  Are you using Pi-hole's DHCP server or your router's?

**Comment by wizard-28** [comment]
> When a device rejoins your network and is unable to resolve DNS, can you run ipconfig /all (or equivalent) to verify it's using the correct DNS server? (that should be the IP of the Pi-hole)

The DNS server address is of my pi-hole (I checked on my mother's android phone).

> If some devices continue to resolve DNS using Pi-hole, while others do not after (re)joining your WiFi, there has to be a configuration issue somewhere.

I noticed that if I keep refreshing the page after it says "DNS address could not be found", after sometime (20 secs), the device is able to connect to the internet normally, but the wifi indicator icon in the status bar still says "Connected but no internet".

This is the case with my laptop too, though the wifi indicator's functioning properly there.

> Are you using Pi-hole's DHCP server or your router's?

Router's

**Comment by wizard-28** [comment]
> I noticed that if I keep refreshing the page after it says "DNS address could not be found", after sometime (20 secs), the device is able to connect to the internet normally, but the wifi indicator icon in the status bar still says "Connected but no internet".

This behavior isn't possible to reproduce using my father's phone, as his phone keeps reconnecting to the network if it detects there's no internet connection.

**Comment by DesktopECHO** [comment]
Can you try assigning one of the problematic devices a static IP and set DNS1 and DNS2 servers to point at Pi-hole's IP?

**Comment by DesktopECHO** [comment]
The ping shown above, what device is this from? 
Take DNS out of the picture all together, try pinging `1.1.1.1` or `8.8.8.8` and see if you still have packet loss. 

It could be an IP conflict.  Assign the Android device running Pi-hole a IP static address outside your DHCP range, making sure the new IP is not already in use by another device.

**Comment by wizard-28** [comment]
> It's not clear from your message if you changed the IP of the Android device running Pi-hole as I advised.

Yeah, I've changed it to static IP, here's the configuration

<table>
<tr>
	<td>IP Address
	<td> 192.168.101.4
<tr>
	<td>Gateway
	<td>192.168.101.1
<tr>
	<td>Network prefix length
	<td>24
<tr>
	<td>DNS 1
	<td>192.168.101.4
</table>

---

```
~
❯ nslookup google.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.67.142
Name:	google.com
Address: 2404:6800:4009:827::200e

~
❯ nslookup gitlab.com
;; connection timed out; no servers could be reached


~ took 15s
❯ nslookup github.com
;; connection timed out; no servers could be reached
```

**Comment by DesktopECHO** [comment]
What is your DHCP range?  You are still using `192.168.101.4` try changing it to something farther away like `192.168.101.168`
What is your setting for DNS 2?  Leaving it blank defaults to 8.8.4.4.  Needs to be explicitly set the same as DNS 1.

**Comment by DesktopECHO** [comment]
Your Linux box has systemd-resolved and returns the DNS server as 127.0.0.x so that gets in the way of our troubleshooting.
Please try this instead: 
`nslookup github.com 192.168.101.168` (Or whatever IP you settle with)

**Comment by wizard-28** [comment]
I changed the router's DHCP range to `192.168.101.2` to `192.168.101.253`, I then assigned the IP `i92.168.101.254` to my pihole, and changed both the DNS to that IP.

Here's the `nslookup` result from my laptop:

```
~
❯ nslookup duckduckgo.com 192.168.101.254
;; connection timed out; no servers could be reached
```

After 30 secs, the wifi magically works as I've described before, and here's the `nslookup` output after that

```
~ took 15s
❯ nslookup duckduckgo.com 192.168.101.254
Server:		192.168.101.254
Address:	192.168.101.254#53

Non-authoritative answer:
Name:	duckduckgo.com
Address: 40.81.94.43
```

**Comment by DesktopECHO** [comment]
> ~ took 15s

Are you still having this issue or is it operating as it should?

Can you send a few pings to your Pi-hole from your Laptop and some other device?
If ping times are still 200-300ms you have a problem somewhere with WiFi.

**Comment by wizard-28** [comment]
> Are you still having this issue or is it operating as it should?

Yes, I'm still having DNS issues. I'm unable to resolve any DNS for about 30 secs after re-connnection. After which, it works (don't ask me how).

---

> Can you send a few pings to your Pi-hole from your Laptop and some other device?
If ping times are still 200-300ms you have a problem somewhere with WiFi.

```
~
❯ ping 192.168.101.254
PING 192.168.101.254 (192.168.101.254) 56(84) bytes of data.
64 bytes from 192.168.101.254: icmp_seq=1 ttl=64 time=86.9 ms
64 bytes from 192.168.101.254: icmp_seq=2 ttl=64 time=25.3 ms
64 bytes from 192.168.101.254: icmp_seq=4 ttl=64 time=124 ms
64 bytes from 192.168.101.254: icmp_seq=5 ttl=64 time=144 ms
64 bytes from 192.168.101.254: icmp_seq=6 ttl=64 time=161 ms
64 bytes from 192.168.101.254: icmp_seq=7 ttl=64 time=78.0 ms
64 bytes from 192.168.101.254: icmp_seq=9 ttl=64 time=117 ms
^C
--- 192.168.101.254 ping statistics ---
9 packets transmitted, 7 received, 22.2222% packet loss, time 8043ms
rtt min/avg/max/mdev = 25.332/105.180/161.212/42.390 ms
```

**Comment by DesktopECHO** [comment]
Something is wrong... 20% packet loss on home WiFi is Not Ok.
Is the Android device's screen on and showing the Pi Deploy UI?  Just want to see if it's power-management related.

**Comment by DesktopECHO** [comment]
You'll need to have the packet loss issue sorted before I can suggest anything else.  
Probably want to verify the issue persists with another device (besides your laptop)

**Comment by wizard-28** [comment]
```
~ $ ping 192.168.101.254
PING 192.168.101.254 (192.168.101.254) 56(84) bytes of data.
64 bytes from 192.168.101.254: icmp_seq=2 ttl=64 time=217 ms
64 bytes from 192.168.101.254: icmp_seq=3 ttl=64 time=135 ms
64 bytes from 192.168.101.254: icmp_seq=4 ttl=64 time=342 ms
64 bytes from 192.168.101.254: icmp_seq=5 ttl=64 time=182 ms
64 bytes from 192.168.101.254: icmp_seq=6 ttl=64 time=306 ms
64 bytes from 192.168.101.254: icmp_seq=7 ttl=64 time=227 ms
64 bytes from 192.168.101.254: icmp_seq=8 ttl=64 time=352 ms
64 bytes from 192.168.101.254: icmp_seq=9 ttl=64 time=456 ms
64 bytes from 192.168.101.254: icmp_seq=11 ttl=64 time=511 ms
64 bytes from 192.168.101.254: icmp_seq=12 ttl=64 time=228 ms
64 bytes from 192.168.101.254: icmp_seq=13 ttl=64 time=353 ms
64 bytes from 192.168.101.254: icmp_seq=14 ttl=64 time=273 ms
64 bytes from 192.168.101.254: icmp_seq=15 ttl=64 time=294 ms
64 bytes from 192.168.101.254: icmp_seq=16 ttl=64 time=111 ms
^C
--- 192.168.101.254 ping statistics ---
17 packets transmitted, 14 received, 17% packet loss, time 16043ms
rtt min/avg/max/mdev = 111.852/285.340/511.787/109.502 ms
```

Here's the ping from my mother's phone (termux)

**Comment by DesktopECHO** [comment]
If you recently flashed a new ROM, you may have better luck rolling back a version or two.  

Try switching WiFi between 2.4 and 5 Ghz if you have that option.  

Just guessing at this point and throwing out random ideas... seems like the Android running Pi-hole has bad WiFi.

**Comment by wizard-28** [comment]
> If you recently flashed a new ROM, you may have better luck rolling back a version or two.
> 
> Try switching WiFi between 2.4 and 5 Ghz if you have that option.
> 
> Just guessing at this point and throwing out random ideas... seems like the Android running Pi-hole has bad WiFi.

I'll flash some other ROM tomorrow, and report back. Thank you a ton for your help till now.

**Comment by wizard-28** [comment]
Well, the phone's battery gave up. I'll buy a RPi in the future and use it as a pi-hole. Thank you nevertheless for this project!
