### ISSUE TITLE
Errors when deploying Raspian to Nexus player (& other 64-bit only ARM CPUs)

### ISSUE THREAD

**Issue by kazukiturbo** [DesktopECHO/Pi-hole-for-Android#41]
Hi there
![20221229_141419](https://user-images.githubusercontent.com/121622603/210003675-a2be5c73-30d5-4161-ade9-e42236cb0b33.jpg)
![20221229_141415](https://user-images.githubusercontent.com/121622603/210003677-b0c05da2-2ce0-4079-84d1-82c5091a741e.jpg)

Thank you so much for your hard work in putting this together.

I tried deploying raspian OS onto my Asus Google Nexus 
![20221229_141630](https://user-
![20221229_141423](https://user-images.githubusercontent.com/121622603/210003674-2bf2f85a-a37e-4baa-a69b-084780c280ea.jpg)
images.githubusercontent.com/121622603/210003654-8e859b7c-95ac-4586-85e0-182f715da982.jpg)
![20221229_141447](https://user-images.githubusercontent.com/121622603/210003672-4064980a-aedd-4a36-96f8-eb9f614e11ab.jpg)
player on Android 8.0

However I have run into the following problems.

I was wondering if you have any tips for me ?

Thank You in advance.

**Comment by DesktopECHO** [comment]
Hi, in the Pi Deploy container options the image URL is:
 `https://github.com/DesktopECHO/Pi-hole-for-Android/releases/download/v3.0.2/raspbian.tgz`

Change this to:
`https://github.com/DesktopECHO/linuxdeploy-images/releases/download/v1.0/raspbian64.tgz`

...and redeploy.

I suspect your device is ARM64 only (like Apple Silicon and some other higher-end ARM processors) so this 64-bit Debian image should work for you.

**Comment by DesktopECHO** [comment]
Related article:

[High-performance ARM chips will be 64-bit only starting in 2022](https://liliputing.com/high-performance-arm-chips-will-be-64-bit-only-starting-in-2022)
