### ISSUE TITLE
Start procedure not displaying all terminal messages

### ISSUE THREAD

**Issue by ThiemoCh** [DesktopECHO/Pi-hole-for-Android#42]
I managed to install on my PIXEL 4a 5g with LineageOS 19.
Deploying worked, but when I hit start, the terminal messages stop after ":: Starting init/sysv: android-raspbian ..."
The system seems to start up normaly otherwise, since I can connect to pi-hole via Browser.
BUT: I can not fetch the generated Password, since it is not displayed, the terminal messages are not shown.
Once I hit Stop terminal messages appear again, but that is of no use regarding the Password.
Can you help?
Kind regards,
Thiemo.

**Comment by DesktopECHO** [comment]
If you wait for a few minutes, does it eventually appear?

To change the password, tap this icon to open the **Properties** menu for the Linux instance:

![image](https://user-images.githubusercontent.com/33142753/212330028-49fdf663-72d4-4894-923c-f2d0f1155e75.png)

Scroll down if needed and change the password here (in this example I chose 'pihole')

![image](https://user-images.githubusercontent.com/33142753/212329625-18dd447c-46c8-4432-a91e-250fea72fd9b.png)

Finally, set the new password by tapping the Options menu (Three dots **⋮** at top right of screen) and tap **Apply Configuration**

![image](https://user-images.githubusercontent.com/33142753/212331877-083cad5d-c8a8-431d-a4d4-3b95157f886c.png)

Now, you will be able to SSH into the Linux instance with the new password you set, and reset the Pi-hole admin password by running the following command:  `pihole -a -p `

![image](https://user-images.githubusercontent.com/33142753/212333944-93936960-071c-47aa-921a-2c37e760feef.png)

**Comment by ThiemoCh** [comment]
I am quite new to LineageOS, so the error might come from that side.
I waited more then 10min for the terminal messages to appear. Since I can connect via Browser, I figured the messages are just not displayed for some reason. I enabled the SSH Option in the app config, but the phone is refusing the connection. To me it looks like this has to do with keys and fingerprints. Also I can not start a Terminal from the burger menu of the app. http://127.0.0.1:5080/cgi-bin/terminal returns Connection Refused. Not sure if that is of any relevance for the problem. I will try to install a terminal-app, many that would give me more options for solving the problem.

**Comment by DesktopECHO** [comment]
The Web Terminal has not been implemented so that's not related.  
Can you also try logging in via RDP?

Also please post the output from the Status menu.  Maybe selinux is getting in the way?

![image](https://user-images.githubusercontent.com/33142753/212377365-8bc5fb5c-b471-42b6-8ef2-2fb85989f089.png)
 

But... there is an option to enable the Telnet Server.  
For testing purposes only, you can go in to settings and enable telnet and disable localhost-only-access, then Telnet to Pi Deploy on port 5023.  Then run `/data/data/com.desktopecho.pideploy/files/bin/pideploy shell` to hop into the Linux instance.

**Comment by ThiemoCh** [comment]
RDP tells me It can't connect because authentication is not implemented.
The Status is this:
![Screenshot_20230113-184000_Pi Deploy](https://user-images.githubusercontent.com/16348900/212386941-8b384612-7dba-428a-8f83-fbfbc469c8f9.png)

Looks like do_status does not return much - strange.
How do I enable Telnet Server? I did not find the option within the app settings.
I have Termux installed locally now if that helps.

**Comment by DesktopECHO** [comment]
Aha ok I see what's up.  Nice phone! 

In the Pi Deploy container options the image URL is:
https://github.com/DesktopECHO/Pi-hole-for-Android/releases/download/v3.0.2/raspbian.tgz

Change this to:
https://github.com/DesktopECHO/linuxdeploy-images/releases/download/v1.0/raspbian64.tgz

...and redeploy.

Snapdragon 855+ and Kryo 4xx+ dropped 32-bit support altogether so you need to use the ARM64 image instead.  You should be good to go after that.

**Comment by ThiemoCh** [comment]
You are my man! 
Thank you, that was it! The solution can be so simple, I even found the telnet option now ;-)
It is a nice phone indeed, bought it used with a cracked display and an Ethernet adapter because you can't get raspberry-pis currently. Thought this was a good Idea. Pi-Hole runs now, let's see if I can add node-red and home assistant or if I run out of memory :)
Thanks again for your quick reply, good work!
Cheers,
Thiemo.
