### ISSUE TITLE
Change Installation size

### ISSUE THREAD

**Issue by ambitiousnuisance** [DesktopECHO/Pi-hole-for-Android#43]
the change installation size is greyed out and set to 2048 mb.. i would like to atleast set 4gb

**Comment by DesktopECHO** [comment]
It’s greyed-out because the default setting is to install to a directory, not an Image file.

**Comment by ambitiousnuisance** [comment]
ohhh. so does that mean that it will only default to 2048mb?
if not, is there a way to change that?
or that ‘size’ won’t matter as it will be installed to a directory?

also, is there a way to change its install location like to an sd card?

**Comment by DesktopECHO** [comment]
Yes, 
**Installation Type** [ Directory or File ]
**Installation Path** [ .\raspbian or .\raspbian.img ]
