### ISSUE TITLE
unbound not installed

### ISSUE THREAD

**Issue by ambitiousnuisance** [DesktopECHO/Pi-hole-for-Android#44]
good day, I yried installing the android apk version, but it seems like that unbound is not getting installed with my instance… i tried set it up as my dns for my phone and on the web interface, the reply keeps getting posted as ‘N/A’ but when i untick the custom dns server (127.0.0.1) and tick 8.8.8.8, the internet works… 

i’m not sure if this is relevant, but when i type ‘unbound’ as a command on the ssh it says that it is an unknown command, conversely, on the legacy version, typing in the same command replies what seems to be a log(?)

**Comment by ambitiousnuisance** [comment]
also, when i try installing unbound using the install command, i always get this message
![Uploading C3F5FDFB-E452-4804-8CD7-4B5F5077914A.png…]()

**Comment by ambitiousnuisance** [comment]
![BCC6B243-CBE4-4749-B154-F8370AA8C117](https://user-images.githubusercontent.com/107865610/215727377-ce3c1edd-76ab-44d2-a33a-a602ca7cdd09.png)

**Comment by DesktopECHO** [comment]
Hi what is the make and model of your device?

**Comment by ambitiousnuisance** [comment]
apparently this is some chinese tablet, running android 5 but reported (fakely) as android 10… its name is MXS C9 [link](https://shp.ee/shccurs)…
