### ISSUE TITLE
Galaxy S5: Read-only file system

### ISSUE THREAD

**Issue by Panagiotis-Zachos** [DesktopECHO/Pi-hole-for-Android#46]
Hi there! Thanks for sharing this great app!

I have an old, rooted Galaxy S5 (SM-G901F) running LineageOS 14.1 with Android 7.1.2.

After installing PiDeploy and selecting "New Deployment" I get the following error log:
```
>>> deploy
## bootstrap/rootfs : do_install && do_configure
:: Installing bootstrap/rootfs ... 
Checking installation path ... mkdir: can't create directory './raspbian': Read-only file system
done
mkdir: can't create directory './raspbian': Read-only file system
Checking file system ... skip
Mounting the container: 
/ ... FUSE exfat 1.2.3
ERROR: failed to open './raspbian': No such file or directory.
mount: mounting ./raspbian on /data/local/raspbian failed: No such file or directory
fail
<<< deploy
```

Here is the status log given by PiDeploy:

```
>>> status
Device: SM-G901F
Android: 7.1.2
Architecture: armv7l
Kernel: 3.10.108-g8c8b947
Memory: 239/1766 MB
Swap: 301/437 MB
SELinux: active
Loop devices: yes
Support binfmt_misc: no
Supported FS: exfat ext2 ext3 ext4 f2fs fuseblk msdos vfat 
Installed system: unknown
Status of components: 
## bootstrap/rootfs : do_status
## core/emulator : do_status
## core/motd : do_status
## core/hosts : do_status
## core/hostname : do_status
## core/mnt : do_status
## core/net : do_status
## core/timezone : do_status
## core/su : do_status
## core/locale : do_status
## core/aid : do_status
## core/profile : do_status
## core/sudo : do_status
## core/unchroot : do_status
## core : do_status
## bootstrap : do_status
## init/sysv : do_status
## init : do_status
Mounted parts: 
<<< status
```

**Comment by DesktopECHO** [comment]
Hi, your problem is right here:

`SELinux: active`

Add this [Magisk module](https://github.com/evdenis/selinux_permissive) **or** install [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger) and you should be set.

**Comment by Panagiotis-Zachos** [comment]
I installed SELinuxModeChanger, set the mode to Permissive and it is set correctly according to the status log. However I am still getting the same error.

**Comment by DesktopECHO** [comment]
Is your device rooted with Magisk or SuperSU/other?  
Did you reboot after flipping to "Permissive"?
Try uninstalling the APK and re-installing.  
Once SELinux is out of the way, I can't see a reason the folder `./rasbian` would have permissions issues.
You can also try going into settings and change `./raspbian` to something like `/data/local/raspbian-root`

**Comment by Panagiotis-Zachos** [comment]
Changing the directory worked, it's now up and running, thanks for the help!
