### ISSUE TITLE
DNS Service Not running 

### ISSUE THREAD

**Issue by rickninja765** [DesktopECHO/Pi-hole-for-Android#47]
It throws error like dns service is not running.
Device Redmi note 4(mido)

**Comment by DesktopECHO** [comment]
Can you post a status log please?  Is SELinux enabled?

**Comment by rickninja765** [comment]
Device: Redmi Note 4
Android: 12
Architecture: aarch64
Kernel: 4.9.325~Fussion
Memory: 44/3574 MB
Swap: 1432/2047 MB
SELinux: active
Loop devices: yes
Support binfmt_misc: no
Supported FS: exfat ext2 ext3 ext4 f2fs fuseblk vfat 
Installed system: Raspbian GNU/Linux 11 (bullseye)
Status of components: 
## bootstrap/rootfs : do_status
## core/emulator : do_status
## core/motd : do_status
## core/hosts : do_status
## core/hostname : do_status
## core/mnt : do_status
## core/net : do_status
## core/timezone : do_status
## core/su : do_status
## core/locale : do_status
## core/aid : do_status
## core/profile : do_status
## core/sudo : do_status
## core/unchroot : do_status
## core : do_status
## bootstrap : do_status
## init/sysv : do_status
## init : do_status
Mounted parts: 
* /
* /proc
* /sys
* /dev
* /dev/shm
* /dev/pts

**Comment by DesktopECHO** [comment]
Hi, your problem is likely right here:

```SELinux: active```

Add this [Magisk module](https://github.com/evdenis/selinux_permissive) or install [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger) then set SELinux to _Permissive_ or _Disabled_.  

Uninstall the app, re-install and re-deploy Raspbian and then see how things look. 

If SELinux is out of the way and you **still** have issues, change the install target (Default is ```./rasbian```) to ```/data/local/raspbian-root```

If you see any errors duing the deployment step, please take a screenshot and send it along.

**Comment by DesktopECHO** [comment]
I see another issue:

In the Pi Deploy container options the image URL is:
https://github.com/DesktopECHO/Pi-hole-for-Android/releases/download/v3.0.2/raspbian.tgz

Change this to:
https://github.com/DesktopECHO/linuxdeploy-images/releases/download/v1.0/raspbian64.tgz

...and redeploy.

I suspect your device is ARM64 only (like Apple Silicon and some other higher-end ARM processors) so this 64-bit Debian image should work for you.

**Comment by rickninja765** [comment]
Not working try both steps.

**Comment by DesktopECHO** [comment]
Hi there,
It does not look like you've deployed the image after changing the install target to ```/data/local/raspbian-root```

Perform the following steps:

- Uninstall APK  
- Reboot
- Reinstal APK
- Set install inage to use 64-bit Raspbian
- Deploy Raspbian image

If it fails, post any useful info (as you've been doing)

**Comment by rickninja765** [comment]
Thanks For Reply man but still. It didn't resolve the issue.

rsyslog ... Starting enhanced syslogd: rsyslogd.
done
sudo ... done
dbus ... Starting system message bus: dbus.
done
lighttpd ... Starting web server: lighttpd2023-04-03 08:33:13: network.c.369) can't bind to socket: 0.0.0.0:80: Address already in use
 failed!
fail
pihole-FTL ... Not running
dnsmasq: failed to create listening socket for port 53: Address already in use
fail
ssh ... Starting OpenBSD Secure Shell server: sshd.
done
unbound ... Starting DNS server: unbound.
done
xrdp ... fail
android-raspbian-status ...  

Might be this error.

![Screenshot_20230403-084016_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229402865-c68ebcaf-8026-4db2-93bf-59f15f354006.png)

![Screenshot_20230403-084002_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229402866-15ce69e5-227a-45b7-9b8c-74f665898419.png)

![Screenshot_20230403-083926_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229402867-283e8db4-155a-4a93-91a4-a0312f8e297c.png)

**Comment by DesktopECHO** [comment]
This indicates Pi-hole was running:
![image](https://user-images.githubusercontent.com/33142753/229680881-3d3655a5-79bb-419b-b900-00f614265663.png)

This indicates SELinux is still enabled:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/33142753/229680288-775324e1-0eab-4672-8833-42cfd627a080.png">

Make sure the instance is not running (Hit STOP) before you try to START it.

**Comment by rickninja765** [comment]
Yeah my bad they are out of sequence.

**Comment by DesktopECHO** [comment]
If you set Pi Deploy to start automatically at boot time, disable that option.
- Reboot your device
- Open Pi Deploy
- Start Raspbian.  Post the output.

**Comment by youareadiesel** [comment]
My problem is the same as the little fella
![Screenshot_2023-04-04-23-45-38-950_com desktopecho pideploy](https://user-images.githubusercontent.com/129919841/229967988-a0902c0a-2004-46af-b265-b95250db0bfd.jpg)

**Comment by rickninja765** [comment]
Same Error So Far

**Comment by DesktopECHO** [comment]
> My problem is the same as the little fella 

This is far too little information to claim it's the same problkem.  

Please create a new issue with info about your device model, and output from Options->Status

**Comment by DesktopECHO** [comment]
> Same Error So Far

We're going in ciricles here.  I can't help if you don't do as I ask. 

> If you set Pi Deploy to start automatically at boot time, disable that option.
> 
> * Reboot your device
> * Open Pi Deploy
> * Start Raspbian.  Post the output.

If any of this is unclear, please ask for clarification.

**Comment by rickninja765** [comment]
By default Pi deploy is disabled from automatically boot. And here I'm putting every screenshot in sequencing order.

![Screenshot_20230405-112038_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229992899-b847e1fd-e646-40d4-95ef-74182a9837f9.png)

![Screenshot_20230405-112050_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229992927-8dab002d-955b-4a37-8c44-b48396d057b7.png)

![Screenshot_20230405-112059_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229992959-bbe1e09a-d519-49d4-a9fa-73d23efe124b.png)

![Screenshot_20230405-112105_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229992969-6b0f8f62-f137-461e-8cfd-3f5df14b23dc.png)

![Screenshot_20230405-112111_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229992979-fa01e854-71d3-47d7-a28d-8ea6fa7559f0.png)

![Screenshot_20230405-112116_Pi Deploy.png](https://user-images.githubusercontent.com/61545131/229992984-6ed0bd28-c2bd-4e82-bd13-93fb083d6a4c.png)

**Comment by rickninja765** [comment]
503 Service Not available ![Screenshot_20230405-152014_Chrome.png](https://user-images.githubusercontent.com/61545131/230046120-95f33aaf-591e-4320-a8e2-445c805f251e.png)

**Comment by DesktopECHO** [comment]
Hmm that's unexepcted.   

Can you press STOP, wait a minure for the processes to halt, then press START again?   Does Pi-hole show as running?   Still getting the 503 error in your browser?

To troubleshoot further, can you ssh into the phone from another computer on your home network?
```ssh android@192.168.0.92```

Or if you have a Windows box, open Remote Desktop Connecton and enter IP ```192.168.0.92```

**Comment by rickninja765** [comment]
After Starting and again starting it worked.
![Screenshot_20230405-162307_Chrome.png](https://user-images.githubusercontent.com/61545131/230060259-d4288697-d5db-4836-9dbd-a8852a81932c.png)

**Comment by DesktopECHO** [comment]
Ok, if you want you can enable the option to autostart Pi-hole at boot.   
You may also need to enable "Lock Screen" and "Wake Lock" in Settings so Android doesn't try to kill idle processes.

Reboot your device and wait 2 minutes for all the services to start.

Check the following:

- Login to Pi-hole Web interface
- Login via SSH

If you can do all of the above then everything is fully working and you are good to go.

**Comment by rickninja765** [comment]
Okay Tried it and yeah it's running good so far..
Btw is it due Arm64 structure? Had problem with load balancing it should be lower than 1
![Screenshot_2023-04-06-12-10-54-97_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/61545131/230296176-561da574-82d2-4de9-92e5-c31ad0a0d2af.jpg)

**Comment by DesktopECHO** [comment]
High load averages are normal on many Android devices… see here or search online.

https://forum.xda-developers.com/t/q-super-high-load-average.1523693/
