### ISSUE TITLE
Web interface not working

### ISSUE THREAD

**Issue by juanmanjarres** [DesktopECHO/Pi-hole-for-Android#49]
Hi, I'm running the app on the Mi 9T Pro and so far it works well and the adblocking works, I can also connect through ssh no problem, but the webserver doesn't seem to be working, it just keeps saying 'refused to connect' on any device I try. 

Here's some screenshots of the status:
![Screenshot_20230411-165751_Pi Deploy](https://user-images.githubusercontent.com/11811569/231306473-51d3127a-b2a9-49a4-ac36-4ac3ef4ac2c1.png)
<img width="354" alt="Screenshot 2023-04-11 at 4 57 36 PM" src="https://user-images.githubusercontent.com/11811569/231306497-917886d2-6ac1-4217-abe7-a2a1197495d0.png">

And when I tried pihole -d, it gave me this error:
<img width="561" alt="Screenshot 2023-04-11 at 5 00 24 PM" src="https://user-images.githubusercontent.com/11811569/231306694-d9879fe3-0c55-4d28-a08c-13a889bd36b8.png">

I already tried #3, but after restarting lighttpd and making sure it's running and everything it still doesn't work. I wonder if there's anything else I should try?

**Comment by DesktopECHO** [comment]
> I already tried #3, but after restarting lighttpd and making sure it's running and everything it still doesn't work. I wonder if there's anything else I should try?

Hi there, what steps did you try from https://github.com/DesktopECHO/Pi-hole-for-Android/issues/3 ?

What's the output from ```sudo lsof -i :80``` and ```sudo  ps -ef | grep lighttpd```

Did you change the port lighttpd uses?  The procedure to change the port has changed since that post.  For example to use port 60080 it would be:

```echo "server.port := 60080" > /etc/lighttpd/conf-enabled/07-port.conf```

...and restart lighttpd or bounce the instance and try going to ```http://172.16.1.85:60080/admin```

**Comment by juanmanjarres** [comment]
> Hi there, what steps did you try from #3 ?

I tried checking the status of lighttpd, and it was already running. I stopped it and restarted it but it was the same. I also checked the port with the `sudo lsof -i :80` command but it didn't have anything so I did not change the port.

> 
> What's the output from `sudo lsof -i :80` and `sudo ps -ef | grep lighttpd`
> 
It gives me this:
<img width="725" alt="Screenshot 2023-04-12 at 3 07 58 PM" src="https://user-images.githubusercontent.com/11811569/231585748-f33d5a16-70a9-45c8-9c98-9fb3f1d7320f.png">

> Did you change the port lighttpd uses? The procedure to change the port has changed since that post. For example to use port 60080 it would be:
> 
> `echo "server.port := 60080" > /etc/lighttpd/conf-enabled/07-port.conf`
> 
> ...and restart lighttpd or bounce the instance and try going to `http://172.16.1.85:60080/admin`

I tried that but it says permission denied, even if I try running it as sudo:

<img width="704" alt="Screenshot 2023-04-12 at 3 10 22 PM" src="https://user-images.githubusercontent.com/11811569/231585856-cb5371c4-1263-446c-a3d6-4637ab8f1df3.png">

**Comment by DesktopECHO** [comment]
Check the status of the service:
``sudo service lighttpd status``

Should return:
``lighttpd is running.``


Next, find which port lighttpd is using:
``sudo ss -4 -l -p -t  -n |  grep light``

This will return something like:
``LISTEN 0      1024         0.0.0.0:80        0.0.0.0:*    users:(("lighttpd",pid=6036,fd=5))  ``

In the example above, lighttpd is running on port 80. 
What does yours show?

**Comment by DesktopECHO** [comment]
On the device, open a browser and try http://127.0.0.1/admin

**Comment by DesktopECHO** [comment]
Checking back on this issue... as you've shown, lighttpd is running so there should be no reason you can't (at the very least) reach the web interface locally on the device.  If it does work but other machines can't the web interface, perhaps your device has a firewall rule in place.  Let me know the outcome when you have a chance.

**Comment by juanmanjarres** [comment]
Sorry, sadly the phone I was running pihole in died two days ago, so I don't have any way of checking what it was anymore, but thank you for the help!
