### ISSUE TITLE
Health status of this list is not showing.

### ISSUE THREAD

**Issue by FDisk80** [DesktopECHO/Pi-hole-for-Android#5]
```
Health status of this list: | List was not downloaded so far
-- | --
This list was added to Pi-hole | 7 minutes ago (2022-01-22 15:18:03)
Database entry was last modified | 6 minutes ago (2022-01-22 15:18:32)
The list contents were last updated | a few seconds ago (2022-01-2215:24:22)
Number of domains on this list: | N/A
Number of invalid domains on this list: | N/A
Database ID of this list: | 35
```
"Health status of this list", "Number of domains on this list", "Number of invalid domains on this list" not showing any info.

While it does actually updates it and working.
This is happening with all the lists in the web UI.
Any idea what might be the issue?

```
[android@localhost ~]$ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 97960 domains
  [i] List stayed unchanged

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  [✓] Status: No changes detected
  [i] Analyzed 34 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  [✓] Status: No changes detected
  [i] Analyzed 2701 domains

  [i] Target: https://dbl.oisd.nl/
  [✓] Status: No changes detected
  [i] Analyzed 1134791 domains

  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 42916 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 57 domains
  [i] List stayed unchanged

  [i] Target: https://v.firebog.net/hosts/static/w3kbl.txt
  [✓] Status: No changes detected
  [i] Analyzed 357 domains

  [i] Target: https://adaway.org/hosts.txt
  [✓] Status: No changes detected
  [i] Analyzed 7525 domains

  [i] Target: https://v.firebog.net/hosts/AdguardDNS.txt
  [✓] Status: No changes detected
  [i] Analyzed 43805 domains

  [i] Target: https://v.firebog.net/hosts/Admiral.txt
  [✓] Status: No changes detected
  [i] Analyzed 636 domains

  [i] Target: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 42292 domains
  [i] List stayed unchanged

  [i] Target: https://v.firebog.net/hosts/Easylist.txt
  [✓] Status: No changes detected
  [i] Analyzed 16300 domains

  [i] Target: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&amp;showintro=0&amp;mimetype=plaintext
  [✓] Status: Retrieval successful
  [i] Received empty file
  [✗] List download failed: using previously cached list
  [i] Analyzed 3676 domains

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  [✓] Status: No changes detected
  [i] Analyzed 9 domains

  [i] Target: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 15267 domains
  [i] List stayed unchanged

  [i] Target: https://v.firebog.net/hosts/Easyprivacy.txt
  [✓] Status: No changes detected
  [i] Analyzed 12881 domains

  [i] Target: https://v.firebog.net/hosts/Prigent-Ads.txt
  [✓] Status: No changes detected
  [i] Analyzed 3670 domains

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 1286 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 378 domains
  [i] List stayed unchanged

  [i] Target: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  [✓] Status: Retrieval successful
  [i] Received empty file
  [✗] List download failed: using previously cached list
  [i] Analyzed 14039 domains

  [i] Target: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/kees1958.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 4826 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 6622 domains
  [i] List stayed unchanged

  [i] Target: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  [✓] Status: Retrieval successful
  [i] Received empty file
  [✗] List download failed: using previously cached list
  [i] Analyzed 1116 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  [✓] Status: No changes detected
  [i] Analyzed 2735 domains

  [i] Target: https://v.firebog.net/hosts/Prigent-Crypto.txt
  [✓] Status: No changes detected
  [i] Analyzed 14148 domains

  [i] Target: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  [✓] Status: No changes detected
  [i] Analyzed 2046 domains

  [i] Target: https://phishing.army/download/phishing_army_blocklist_extended.txt
  [✓] Status: No changes detected
  [i] Analyzed 53981 domains

  [i] Target: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 325 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 8148 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 2202 domains
  [i] List stayed unchanged

  [i] Target: https://urlhaus.abuse.ch/downloads/hostfile/
  [✗] Status: Connection Refused
  [✗] List download failed: using previously cached list
  [i] Analyzed 1315 domains

  [i] Target: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
  [✓] Status: No changes detected
  [i] Analyzed 3496 domains

  [i] Target: https://raw.githubusercontent.com/llacb47/mischosts/master/tiktok-hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 184 domains
  [i] List stayed unchanged

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
```

**Comment by DesktopECHO** [comment]
No idea, but that's a lot of lists.  Does it exhibit the same issue when you only have one list?

**Comment by FDisk80** [comment]
> No idea, but that's a lot of lists. Does it exhibit the same issue when you only have one list?

Yes, the same even with one list.

**Comment by ashishkotnala29** [comment]
Can confirm there's no status shown here.
![image](https://user-images.githubusercontent.com/18037179/151301630-c1634290-81da-4d45-b21e-e72d687c0af5.png)

**Comment by DesktopECHO** [comment]
Hello., Can you confirm the date and time are correct on your Android device?

**Comment by ashishkotnala29** [comment]
Yes, definitely it's network synced.
![image](https://user-images.githubusercontent.com/18037179/151304449-22866411-6efc-4c20-9c24-7c3554534388.png)

**Comment by FDisk80** [comment]
> Hello., Can you confirm the date and time are correct on your Android device?

Yes, date and time is correct.

**Comment by DesktopECHO** [comment]
Confirmed on my lab machine - This is an issue.  

Does anyone know if this is happening on non-containerized CentOS 7 as well?

**Comment by ashishkotnala29** [comment]
Happens on x86 as well. Seems like an upstream issue.

![image](https://user-images.githubusercontent.com/18037179/151396606-8b7e6d67-27f2-4a1e-811d-04f83ab0e211.png)


![image](https://user-images.githubusercontent.com/18037179/151396555-d8cb37f6-15a2-471f-8cd9-75eab1aece5f.png)

**Comment by DesktopECHO** [comment]
Updating sqlite3 and reinstalling Pi-hole seems to have fixed the issue.   My RPM's are [here](https://github.com/DesktopECHO/CentOS7-ARMv7)

![image](https://user-images.githubusercontent.com/33142753/151433720-0eb346c3-561f-4188-b296-8825d8370129.png)

**Comment by ashishkotnala29** [comment]
That's great. Is reinstalling pi-hole a must?

**Comment by DesktopECHO** [comment]
Not sure, you can give it a try.  I was pretty heavy-handed with it, just ran ``p4a-install`` and let it do its thing.

**Comment by FDisk80** [comment]
> sqlite3

M

**Comment by ashishkotnala29** [comment]
@DesktopECHO Okay, I'll try that on another device later. Don't wanna mess up my working instance right now.

**Comment by ashishkotnala29** [comment]
> Nice. What is the proper way to update sqlite3?

Just update the RPMs using `rpm -Uvh sqlite*.rpm`

**Comment by DesktopECHO** [comment]
> Nice. What is the proper way to update sqlite3?

Download ``sqlite-libs-3.36.0-4.el7.armv7hl.rpm`` and ``sqlite-libs-3.36.0-4.el7.armv7hl.rpm`` and install with ``rpm -Uvh``

**Comment by ashishkotnala29** [comment]
No need to restart pi-hole. Update RPM and run `pihole -g`. Web-UI shows the icons and status fine now.

**Comment by DesktopECHO** [comment]
> Happens on x86 as well. Seems like an upstream issue.
>
Thanks Ashish for verifying this!

**Comment by ashishkotnala29** [comment]
@DesktopECHO Thank you for quickly identifying the fix. Seems like centos 7 is showing its age now. But then what choice do we have on kernel 3.0.x...

**Comment by FDisk80** [comment]
> Download `sqlite-libs-3.36.0-4.el7.armv7hl.rpm` and `sqlite-3.36.0-4.el7.armv7hl.rpm` and install with `rpm -Uvh`

I'm getting "not an rpm package (or package manifest)" when trying to install those 2 packages.

**Comment by DesktopECHO** [comment]
How did you download the RPM’s?  Can you show a list of the files and their sizes please?

**Comment by FDisk80** [comment]
> How did you download the RPM’s? Can you show a list of the files and their sizes please?

Never mind, doing it like this worked perfectly:
`rpm -Uvh https://github.com/DesktopECHO/CentOS7-ARMv7/raw/main/sqlite-libs-3.36.0-4.el7.armv7hl.rpm
`
`rpm -Uvh https://github.com/DesktopECHO/CentOS7-ARMv7/raw/main/sqlite-3.36.0-4.el7.armv7hl.rpm`

Not sure why it would not work if I downloaded the file first.

**Comment by DesktopECHO** [comment]
> @DesktopECHO Thank you for quickly identifying the fix. Seems like centos 7 is showing its age now. But then what choice do we have on kernel 3.0.x...

Indeed!  I'm glad they are still supporting CentOS 7 but I suspect this will be a recurring issue as it ages.

Are you sure you want to close [Pi-hole #4580](https://github.com/pi-hole/pi-hole/issues/4580)?  This issue [affects Ubuntu 16.04 as well](https://www.reddit.com/r/pihole/comments/sdxq2k/incorrect_health_status_of_adlist), and I'm thinking the 'more correct' thing to do is fix this issue the same way Git was dealt with (in other words, make Pi-hole work with older versions of sqlite3 rather than requiring a library outside of the CentOS/EPEL/Remi repos.)
