### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by LeBazarDeBryan** [DesktopECHO/Pi-hole-for-Android#50]
Hello, i was reinstalling  Pi-Hole on my Samsung Galaxy S8 (Stock) with A2N Kernel (Permissive) and i get this error :

<img src="https://user-images.githubusercontent.com/85786075/231454114-a796b3b2-c805-4bc1-96ae-faea2ad45fb2.jpg" height="900" width="450" />

<h2> Status </h2>

<img src="https://user-images.githubusercontent.com/85786075/231455737-a66e6372-bb80-4dcf-9d7b-f9a4d9de3819.jpg" height="700" width="450" />

Any idea or solution ?

Thanks.

**Comment by LeBazarDeBryan** [comment]
Thanks but it doesn't work.
I flash <a href="https://mega.nz/file/4IRmyCwD#SuzZB78pDv2NSD0KSb___y2_p-AHf0A4VWkwHlDy8ls"> Know Remover </a> so i don't know if it's Knox.
I think i'm gonna flash LineageOS but do you know what is the best version of LineageOS ?

**Comment by DesktopECHO** [comment]
Unfortunately I don't have that device so I can't say for certain. 

Head over to [XDA](https://forum.xda-developers.com/f/samsung-galaxy-s8-s8-cross-device-development.6471/) and pick a LineageOS ROM that looks like a good match for your device.

**Comment by LeBazarDeBryan** [comment]
Thanks.
