### ISSUE TITLE
Pi-Hole not working

### ISSUE THREAD

**Issue by LeBazarDeBryan** [DesktopECHO/Pi-hole-for-Android#51]
Hi, The web interface work but the pi-hole doesn't block ads.

<h2 align="center"> Status </h2>
<img src="https://user-images.githubusercontent.com/85786075/231511734-f8e761aa-b8ea-492f-b831-60dda35121f9.png" />

Any idea ?
Thanks.

**Comment by DesktopECHO** [comment]
If mobile data (3G/4G/5G) is enabled, turn it off.
In WiFi settings, make sure DNS1 and DNS2 are both set to `````127.0.0.1`````

**Comment by DesktopECHO** [comment]
1 - Make sure Private DNS is disabled:  [Android Docs](https://support.google.com/android/answer/9654714?hl=en#zippy=%2Cprivate-dns)

2 - Try disabling IPv6:
`````
sudo bash
echo 0 > /proc/sys/net/ipv6/conf/wlan0/accept_ra
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
exit
`````
..then try to browse the Web on your device.  Look in the query logs to see if Pi-hole is answering the queries.

**Comment by LeBazarDeBryan** [comment]
![image](https://user-images.githubusercontent.com/85786075/231992182-7e78be91-2f36-4906-a696-0b15df8c761b.png)

I tried the solutions but it doesn't work, i do the adblock test at 10:42 and it doesn't block.
The Private DNS was on Automatic so i disable it, i reboot and it doesn't work.
I try disabling the IPv6 but doesn't work.

**Comment by LeBazarDeBryan** [comment]
Wait... In the Query Log it say that it's blocking Ads but on my PC it's not blocking Ads.
Weird...
![image](https://user-images.githubusercontent.com/85786075/232132913-84bd1874-0be3-447b-a1e8-c78fc9f4eab7.png)
DESKTOP-BRYAN is my PC

**Comment by LeBazarDeBryan** [comment]
I find the Solution !!

In the Query Log it said it was blocking but it was really blocking the problem was my P,  it's because of the IPv6 !
You can disable it by going in the **Control Panel** > **Network and Internet** > **Center Network and sharing** > **WiFi** > **Property** > and disable **Internet Protocol version 6 (TCP/IPv6)**.
