### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by youareadiesel** [DesktopECHO/Pi-hole-for-Android#52]
Well, a few days ago i followed the same instructions in #47 and it worked i tested it in some ad testers sites, But now i retried the process, and it does show me is enabled, however it won't block any ad
![Screenshot_2023-04-12-13-48-26-097_com desktopecho pideploy](https://user-images.githubusercontent.com/129919841/231532583-4c89a830-5b95-493b-953b-4425ba8a51aa.jpg)
![Screenshot_2023-04-12-13-49-19-713_com android chrome](https://user-images.githubusercontent.com/129919841/231532592-4d13f729-04ef-47bd-b011-300d0492367a.jpg)

**Comment by youareadiesel** [comment]
Also, this is my current status


![Screenshot_2023-04-12-14-13-02-617_com desktopecho pideploy](https://user-images.githubusercontent.com/129919841/231532859-ff50aea3-e963-442b-b6a8-07e988270915.jpg)

**Comment by DesktopECHO** [comment]
Can you login to the Pi-hole admin page and see the query log?

If mobile data (3G/4G/5G) is enabled, turn it off.
In WiFi settings, make sure DNS1 and DNS2 are both set to `````127.0.0.1`````

**Comment by youareadiesel** [comment]
![Screenshot_2023-04-13-02-47-24-350_com android chrome](https://user-images.githubusercontent.com/129919841/231769342-2261bbce-00d9-43a3-8090-7f58271724e7.jpg)


![Screenshot_2023-04-13-02-49-48-856_com android chrome](https://user-images.githubusercontent.com/129919841/231769126-e78f3c42-6c74-43ed-a7f8-21534eada232.jpg)


About the dns, does i have to change it into my router ? In my one this option doesn't show me

**Comment by DesktopECHO** [comment]
1 - Make sure Private DNS is disabled:  [Android Docs](https://support.google.com/android/answer/9654714?hl=en#zippy=%2Cprivate-dns)

2 - Try disabling IPv6:
`````
sudo bash
echo 0 > /proc/sys/net/ipv6/conf/wlan0/accept_ra
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
exit
`````
..then try to browse the Web on your device.  Look in the query logs to see if Pi-hole is answering the queries. 

> About the dns, does i have to change it into my router ? In my one this option doesn't show me

Have a look at the official Pi-hole documentation: [How do I configure my devices to use Pi-hole as their DNS server?](https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245)
