### ISSUE TITLE
Pihole causing connectivity issues on other Android devices

### ISSUE THREAD

**Issue by BoboMuller** [DesktopECHO/Pi-hole-for-Android#55]
Hello dear developer and everyone reading,
installing this fork of Linuxdeploy made my life definitely easier setting all of this up but there is one really strange issue that I haven't seen here or in other places on the internet.

First things first:
My setup is an old Xiaomi note 4 (mido) with a Syberia Android 10 custom rom and root with SELinux by default set to permissive.

When I installed the app and set up the pihole the usual installation flow was almost instantly interrupted for a short moment with the error: "wget: write error: broken pipe" (two times)
But I did not care, since it worked out and I could start sucessfully. 
I can access the site and also ssh without issues, but every time I restart the Pihole I get a message saying: "yes: standard output: Broken pipe" followed by the normal as it should startup.
The Pihole is also working and does its job but from time to time there is something strange happening.

My other Android devices in the home (MAC adresses set to static) lose their connection every second and try to reconnect in a loop.
I found out that I can solve this by double tapping the device with Pihole and going into the app, but doing this every hour is going to drive everyone insane. 
This issue is not affecting the Laptop, TV (not Android), Vaccuum and so on. 

I thought that this is happening because of power saving features of the Note 4, so I disabled everything possible but this did not help at all unfortunately. The settings in the Pideploy app are also still activated so the CPU has work to do when the screen is off.

Also there is one more thing and I guess it is directly related to the issue above.
From time to time the log in the Pideploy app gets a bit larger and it is always the same messages:

```
>>> stop
## core/net : do_stop
<<< stop
>>> start
## core/net : do_start
<<< start 
(and so on)

```

**Comment by DesktopECHO** [comment]
> When I installed the app and set up the pihole the usual installation flow was almost instantly interrupted for a short moment with the error: "wget: write error: broken pipe" (two times)

This is not normal, seems like a loss of internet connectivity while downloading the Raspbian image.  Redeploy and don't trust the image until it downloads without errors.

**Comment by BoboMuller** [comment]
So I tried this now many many times, but the result did not get better. In one retry it was so broken that the startup printed out scrambles of the shell commands as if they were just strings. Is there another way like pulling the image from the local storage or local device if this is really the issue here?
Another fun problem this caused is that other phones than mine where a new MAC adress is generated on every connect just clogged the ip range of my DHCP in the Fritzbox. For everyone reading this in the future: Deactivate the ranomisation in the network settings on the phone.

**Comment by DesktopECHO** [comment]
Hi, switch to the 64-bit image.
In the Pi Deploy container options the image URL is:
 `https://github.com/DesktopECHO/Pi-hole-for-Android/releases/download/v3.0.2/raspbian.tgz`

Change this to:
`https://github.com/DesktopECHO/linuxdeploy-images/releases/download/v1.0/raspbian64.tgz`

Reboot and redeploy.

**Comment by BoboMuller** [comment]
Hi,
this indeed helped and now there is no weird output to the log with starting and stoping but the main issue remained unfortunately. My other Androids have problems every one or two hours and start connecting and disconnecting every second. 
Best regards!

**Comment by DesktopECHO** [comment]
> My other Androids have problems every one or two hours and start connecting and disconnecting every second.

[Disable MAC randomization](https://source.android.com/docs/core/connect/wifi-mac-randomization-behavior#:~:text=The%20Android%20framework%20uses%20two,to%20a%20Wi%2DFi%20network.) on the device running Pi-hole and your other Android devices.  The way to do this varies by version and manufacturer but the approximate steps are:
 
**1:**  Go to the Settings app on your Android device.
**2:** Tap on Network & Internet or Connections > Wi-Fi.
**3:** Tap the gear icon next to the Wi-Fi name of the router or node your device is connected to. 
**4:** Tap on MAC address type.
**5:** Select **Use phone MAC** (or **Use device MAC**).
**6:** Disconnect and reconnect to WiFi 
**7:** Open Pi-deploy and [ ■ STOP ] the instance, wait a few seconds and [ ⏵ START ] it back up.

**Comment by BoboMuller** [comment]
Thanks for your response. MAC randomization was off from the beginning because it causes many other problems as well (mostly things like blocking all IPs of the dhcp range)

**Comment by BoboMuller** [comment]
Hi,
this command does not return any output unfortunately.
I have looked into the log and there is nothing worth mentioning. Everything seems to work as it should.
The only thing happening is that around this time the log is flooded, because every time the device connects for half a second, it creates tons of DNS requests

**Comment by DesktopECHO** [comment]
> I found out that I can solve this by double tapping the device with Pihole and going into the app, but doing this every hour is going to drive everyone insane.

I think I misunderstood your issue.  

What's happens is Pi-hole 'dies' when it's not a foreground app, is that correcrt?

If that's the case, the OOM killer in your Android build may be too agressive.   Maybe see if settings available here can help:
https://github.com/syberia-project/platform_system_memory_lmkd

**Comment by DesktopECHO** [comment]
Can you un-check these options:

![Untitled](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/b6e18a71-884e-4c17-9fe4-93e983dc0935)

Reboot Device

Re-enable **Lock Wi-Fi** and **Wake Lock** 

See if that helps.

**Comment by BoboMuller** [comment]
This seems to make the issue even worse. Now I have the problem every 10 minutes after the screen of the PI-hole host turns off. 
One more thing I noticed is that my Windows pc is actually affected as well but I just did not notice it because everything seemed to work. One example is that when this issue starts I cannot connect to my router, even through the ip of the router (Fritzbox usually uses 192.168.178.1).
This is solved however after stopping and starting the PI-hole

**Comment by BoboMuller** [comment]
I do not have time for resolving this up to next month so for now I solved this by using the usb port of the wifi for charging and keep the screen on with image calibration set to almost 0 so that the screen is forced to be almost off

**Comment by DesktopECHO** [comment]
Similar issue to this: https://github.com/meefik/linuxdeploy/issues/1092

There are a couple of things you can try as well in the thred linked above.

Also have a look at https://play.google.com/store/apps/details?id=eu.thedarken.wldonate&hl=en&gl=US

**Comment by BoboMuller** [comment]
Hey, I just want to finally close this once and for all since it seems that I finally found the issue that was maybe causing all of this.
When configuring the PIHole I instruced the router to hand out a static IP to the device, but in the end it was not that static after all. After one day or so it would hand out a new one anyway and then the router would point to a ipv6 DNS adress that is not existing anymore. 
You can solve this by registering your link local ipv6 in the router. This one won't change for sure. Hopefully this helps someone.
