### ISSUE TITLE
Steps to get root access over ssh in legacy devices(specifically samsung)

### ISSUE THREAD

**Issue by falekunal** [DesktopECHO/Pi-hole-for-Android#56]
# Updating pi hole adlist can be done in two ways, 
## 2. Through ssh or remote desktop connection.

But in my case I was not able update adlist by any of them. When I perform a update command  `pihole -g` I was getting error `sudo: PERM_ROOT: setresuid(0, -1, -1): Permission denied`.
 
### It can be solved by setting the username -> `root` and password -> `toor` before starting installation.

ssh using `ssh root@192.168.0.111` and password as `toor` can give root access to update adlist. (here `192.168.0.111` was my local ip assigned for deivce on which pi hole was installed, so change it accordingly.).

**Comment by DesktopECHO** [comment]
Not sure why you were having trouble.  I ran `pihole -g` on a couple of devices in my lab without issue:

`````
android@walleye:~$ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Imported 182498 domains, ignoring 1 non-domain entries
      Sample of non-domain entries:
        - 0.0.0.0
  [i] List has been updated

  [✓] Creating new gravity databases
  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 182498 (182498 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
android@walleye:~$ 
`````
If you have a really old kernel, like from a Galaxy S2 or similar era, you may need this added to `````sshd_config`````:
`````UsePrivilegeSeparation no`````
