### ISSUE TITLE
Unable to reach pihole on any device but the phone itself

### ISSUE THREAD

**Issue by MerGr** [DesktopECHO/Pi-hole-for-Android#57]
Hello, I've been trying to get pihole to be accessible to the router and other devices on the local network to no avail, lighttpd is running and I tried reatarting to dodgy results. Ports are correctly used by lighttpd (port 80) and I can access the pihole from the device itself, but none other, either via web interface, ssh or rdp, the phone is a rooted Samsung Galaxy J1 2016 running unofficial LineageOS 14.1 (Android 7.1.2)

**Comment by DesktopECHO** [comment]
Are you able to ping the IP address of the device running Pi-hole, from another device on your network?

**Comment by MerGr** [comment]
No I can't reach the pihole, sometimes it starts becoming accessible again, sometimes not

**Comment by DesktopECHO** [comment]
Make sure your Galaxy J1 is being charged, the device is awake, and the Pi-deploy app is shown on-screen.  
When you do this, can you reliably ping the device?

**Comment by MerGr** [comment]
weirdly enough it's started working today, if it persists I will close this issue

**Comment by MerGr** [comment]
it stopped being reachable again, pinging the IP gives Destination Host Unreachable error

**Comment by DesktopECHO** [comment]
> it stopped being reachable again, pinging the IP gives Destination Host Unreachable error

Make sure your Galaxy J1 is being charged, the device is awake, and the Pi-deploy app is shown on-screen.

When you do this, can you reliably ping the device?

**Comment by MerGr** [comment]
if it helps, Pideploy says that plymouth fails

**Comment by DesktopECHO** [comment]
Can you un-check these options:

![Untitled](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/b6e18a71-884e-4c17-9fe4-93e983dc0935)

Reboot Device

Re-enable **Lock Wi-Fi** and **Wake Lock** (and **Lock Screen** if needed)

**Comment by MerGr** [comment]
Now it just says "Connection Timeout", pinging the pihole gives a request timed out error

**Comment by MerGr** [comment]
I tried it on a different device (STG H10, Cortex A53, 2GB), same result, unreachable except on the device itself

**Comment by DesktopECHO** [comment]
No idea what's up with your WiFi, not seeing this anywhere else.

**Comment by MerGr** [comment]
I guessed as much, so I flashed OpenWRT on my router (Xiaomi Router 4A 100M International Edition) and my pihole is accessible immediately and working, I'll give it a day and if it's still accessible I'm closing the issue

**Comment by MerGr** [comment]
Problem solved, seems installing OpenWRT did the trick
