### ISSUE TITLE
Can't install PIXEL Desktop

### ISSUE THREAD

**Issue by Dpoint1** [DesktopECHO/Pi-hole-for-Android#58]
Hi, i tried to install pixel desktop using the command pideploy-gui-install and this is what i got:

Hit [Enter] to install Raspbian PIXEL Desktop environment, CTRL-C to exit 
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease                                      
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]                         
Fetched 15.0 kB in 4s (4,027 B/s)                          
Reading package lists... Done
Reading package lists... Done
E: Unsupported file ./libgnome-keyring-common_3.12.0-1_all.deb given on commandline
E: Unsupported file ./libgnome-keyring0_3.12.0-1+b2_armhf.deb given on commandline
E: Unsupported file ./gksu_2.0.2-9+b1_armhf.deb given on commandline
E: Unsupported file ./libgksu2-0_2.0.13~pre1-9+b1_armhf.deb given on commandline
E: Unsupported file ./libgtop-2.0-10_2.34.2-1_armhf.deb given on commandline
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
rpi-chromium-mods is already the newest version (20220711).
0 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.
mv: cannot stat '/usr/bin/lxpolkit': No such file or directory
/usr/local/bin/pideploy-gui-install: line 38: gconftool: command not found

is there a solution to this? Thanks:)

**Comment by DesktopECHO** [comment]
Source files were moved.  I updated the script, install it by running:

`````
sudo curl --output /usr/local/bin/pideploy-gui-install https://raw.githubusercontent.com/DesktopECHO/Pi-hole-for-Android/main/usr/local/bin/pideploy-gui-install 
`````
Like so:
`````
android@douglas:~$ sudo curl --output /usr/local/bin/pideploy-gui-install https://raw.githubusercontent.com/DesktopECHO/Pi-hole-for-Android/main/usr/local/bin/pideploy-gui-install 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2054  100  2054    0     0   9553      0 --:--:-- --:--:-- --:--:--  9553
`````
Then try running the installer (don't use sudo)

`````
android@douglas:~$ pideploy-gui-install 
`````

**Comment by DesktopECHO** [comment]
Just gave this updated script a whirl on my low-end test device.  
PIXEL Desktop over RDP to an old Android HDMI stick running Lolipop.  Not bad! 
![images-removebg-preview](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/86814ae8-c229-4653-9d0c-0b744ff283d1)
![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/f25ff018-3a32-4702-a9b2-0c1942a1f827)

**Comment by Dpoint1** [comment]
![Screenshot_20230526_092946_Microsoft Remote Desktop](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/134495457/5dd8e7a5-79b5-4c03-92a6-ba074b900ea6)
It worked! 
Thanks:)
