### ISSUE TITLE
Importing rootfs from tar.gz archive... fail

### ISSUE THREAD

**Issue by JamsHDs** [DesktopECHO/Pi-hole-for-Android#59]
Android TV Box 4.4.2 Kitkat i followed the guide and this is the error i get.

Importing rootfs from tar.gz archive... fail

**Comment by JamsHDs** [comment]
1s: /data/local/mnt/etc/rc/local/: not found

**Comment by DesktopECHO** [comment]
Normally Android 5 Lollipop is the oldest version of Android that's supported.  
Did you follow the instructions and download the image for older (4.x) devices?

**Comment by JamsHDs** [comment]
You need to remove the application directory: /data/data/ru.meefik.linuxdeploy  how do i do this step?

**Comment by DesktopECHO** [comment]
Uninstall Pi-Deploy and Linux Deploy Apps if they are on your device.

Reboot

For Android 4.x, install Linux Deploy and follow the installation steps here:
https://github.com/DesktopECHO/Pi-hole-for-Android/tree/legacy

Make sure SElinux is **not** set to Enforce

**Comment by JamsHDs** [comment]
I'll try this tomorrow, thanks for the quick reply!
