### ISSUE TITLE
Samsung Tab S2 - cannot deactivate SELinux Enforce because Inkernel SeLinux

### ISSUE THREAD

**Issue by Sinusflorian** [DesktopECHO/Pi-hole-for-Android#6]
Hello Here are i'm again^^ Ok i got finally Rooted my Samsung Tab 2 SM-T 813 (after 3 Failures and 1 Brick i was able to Root the Stock Samsung OS from 2016) and followed your Steps Carefully. Ok now next Huge Problem, when i try to install the Script in the Linux deplolyer it says permission denied on mass. I looked in the Internet and it is caused by the INKERNEL integrated SELinux Enforce mode (Knox) (yes i tried to delete the App but it gets instant installed from the Inkernel. And no LinuxSeSwitcher dont work, it says permissive is sent to system but in systeminfo it stays enforced AND after reboot to. I Even installed that Busybox thingy. ^^

So i have to search for a Custom ROM. But... my Nerves are Momentarly at zero lol. I need Guidance pls lol, just as i sayd in my previous post on the Windows 10 Pi-Hole Thread that i'm not so good at Programming things, i just want to get that Pi-Hole worked on android, so that i can relax. ^^ But when it's too complicated i will stick to the Brave Browser lol.

I say already thanks for Reading this.

**Comment by DesktopECHO** [comment]
I can't give you any guarantees but this looks like a good ROM to try:

[https://forum.xda-developers.com/t/rom-official-t813-9-lineageos-16-0.3829962/](https://forum.xda-developers.com/t/rom-official-t813-9-lineageos-16-0.3829962/)

Congratulations for getting this far!

**Comment by Sinusflorian** [comment]
Hello here i am again. I succsessfully Flashed Lineage 16 OS on my Tablet. 🤓 After endless Sitelookings i did it lol. Oooff it was hard xD I say it to everyone who reads this ^^ Tab s2 is horrible to flash for people like with me with zero experience on Linux and Androidmodding thingys lol.... no Fastboot per stock, Selinux lock. Had to combine 3 or 4 Guides to did it haha.

But now the install procsess for the Pi-Hole is failing on the finish line with Segment errors ^^

I attach the log. 
[output.log](https://github.com/DesktopECHO/Pi-hole-for-Android/files/7972770/output.log)

I hope that the error is not so fatal like the first with the locked enforced in Kernel. 🤣

But huge thanks for the Link, the Guide was a great Foundation.

Maybe you can help again, thanks again for reading. :)

**Comment by DesktopECHO** [comment]
Hi, unfortunately I have no idea why your device is being so stubborn.  I've had 100% success with any old ARMv7 Android device I've come across, except for these Galaxy Tab devices.  

Let's see if anyone out there can offer some suggetions... https://github.com/meefik/linuxdeploy/issues/1300

**Comment by DesktopECHO** [comment]
The only other thing I can come up with is you may need to install the [LineageOS su ](https://download.lineageos.org/extras)
Not something I've done before so can't offer any guidance unfortunately, short of this link [I googled](https://nerdschalk.com/root-lineage-os-su-addon-zip-download/).  
Good luck and tread carefully!

**Comment by DesktopECHO** [comment]
Also can you confirm your root is working properly?  Check with [this app](https://play.google.com/store/apps/details?id=com.joeykrim.rootcheck)

**Comment by Paft** [comment]
_Absolutely unhelpful comment:_ I'm also on **LineageOS** (14.0) for a Moto G 1st gen. It's been running solid for a week. LineageOS seems better than the stock ROM. My WiFi kept dropping when I locked the device. All good now.

16.0 was also working, but that was an UNOFFICIAL update and I was encountering a 'phone is starting...' bug randomly.

**Comment by DesktopECHO** [comment]
> _Absolutely unhelpful comment:_ I'm also on **LineageOS** (14.0) for a Moto G 1st gen. It's been running solid for a week. LineageOS seems better than the stock ROM. My WiFi kept dropping when I locked the device with stock. All good now.
> 
> 
> 
> I only needed to install **Magisk** and follow the instructions on the main page.
> 
> 
> 
> 16.0 was also working, but that was an UNOFFICIAL update and I was encountering a 'phone is starting...' bug randomly.  

Question - What does your experience with LineageOS on a Moto G have to do with this   particular issue on a Galaxy Tab 2?

**Comment by Sinusflorian** [comment]
Ooofff i thank you much, much! 😊

I'm tempted to donate you a 10 Euro for a Coffee or so, you deserved it. 👍

And the other Thing: When you need full remote access just say it, have nothing important thingys on the Tablet, i used before for it for little Youtube/Twitch relax or gaming with my best Friend, also when you want to full inspect it, then its ok. 👍

And pls don't stress it, take your Time. 😊👍

**Comment by DesktopECHO** [comment]
Give this a try: [p4a15-arm64.tar.gz](https://1drv.ms/u/s!AgXpn0Tw0i5-kcUSyZC4ai84n8TGhw?e=SdwlsC)
Same instructions as the original image.

**Comment by Sinusflorian** [comment]
Hello, have very good news! It's work! And exremly gold too! 👍  I Thank you sooo much for helping and patience With me! It blocks even 90% of the YouTube app Ads for me. But a little Warning: Don't get crazy with 10k blocklistentries ^^ it will crash your Tablet and then you have to reinstall it xD Here some pictures :)

I let the thread open, when you have questions. :)

Have a Nice day/night! 😊

![Screenshot_20220205-202138](https://user-images.githubusercontent.com/93134772/152656163-95659513-fc08-440d-a7e7-812e4de33caf.png)
![Screenshot_20220205-202149](https://user-images.githubusercontent.com/93134772/152656166-5ad68b40-8323-4140-acfe-b4102040655d.png)
![Screenshot_20220205-201754](https://user-images.githubusercontent.com/93134772/152656168-8e525d8c-8967-4b37-a6ef-376baa4489a0.png)
![Screenshot_20220205-201851](https://user-images.githubusercontent.com/93134772/152656170-6c3b80a0-67e2-4088-a8c4-a820c7c1be77.png)

**Comment by DesktopECHO** [comment]
That's great news!  
If you want to donate, please give directly to the Pi-hole folks.  Good luck!
