### ISSUE TITLE
move app/data to external sdcard

### ISSUE THREAD

**Issue by chamelo003** [DesktopECHO/Pi-hole-for-Android#64]
Can the app or data be moved.to external sdcard? I'm asking because I'm trying to load it on a very old android tv stick that I got laying there, but it's internat storage is only 4G. So I want to know if someone has tried to move it to external sdcard, I've tried with AppMgrII and no luck. My device is rooted.

**Comment by DesktopECHO** [comment]
In Raspbian Properties under Installation Type, the default is **Directory**.  You can try changing that to **File** and set the path to your SDcard.  The path can vary by manufacturer, typical example is `````/mnt/sdcard/raspbian.img`````

**Comment by chamelo003** [comment]
> In Raspbian Properties under Installation Type, the default is **Directory**. You can try changing that to **File** and set the path to your SDcard. The path can vary by manufacturer, typical example is `/mnt/sdcard/raspbian.img`

Thanks for your reply, I did that already and it works.

**Comment by SonThanhVN** [comment]
does it also save data and files on the SDCard ?
like adlist and logs ?

**Comment by chamelo003** [comment]
> does it also save data and files on the SDCard ? like adlist and logs ?

Long story short: yes, as long as your .IMG size have free space.

**Comment by SonThanhVN** [comment]
> > does it also save data and files on the SDCard ? like adlist and logs ?
> 
> Long story short: yes, as long as your .IMG size have free space.

for some reason my raspbian.img keep install on internal drive insted of the SD Card

**Comment by SonThanhVN** [comment]
the SD card have 32GB btw

**Comment by chamelo003** [comment]
Son the first screenshot were you ran the df command looks like your SD card isn't mounted, that's why your installation defaults to internal storage, btw what format is your SD card? Because fat32 only allows 3.9G files (which is my case) I'm not sure if you can format your SD card ext3 and be read by the device (it should) but as I mentioned before, I'm not sure. You can try though.
