### ISSUE TITLE
Update to the latest version? 

### ISSUE THREAD

**Issue by Akszyn** [DesktopECHO/Pi-hole-for-Android#67]
Is there a chance that a new apk file will be released with the latest components with the ability to synchronize between devices with this app installed, eg using gravity sync and possibly with the option to change or remove the password for easier integration with various services like home assistant?

**Comment by DesktopECHO** [comment]
You should be able to ssh into the Raspbian instance and do any of those things.  `pihole -a -p` to change/clear the password.

**Comment by Akszyn** [comment]
So as I understand there is no chance for a new apk file with a newer pi-hole and gravity sync?

**Comment by DesktopECHO** [comment]
When you deploy a container, at first-run it downloads and installs the latest Pi-hole code.  Gravity sync is something totally separate and not included with the image.

Can you reach the web admin page from other computers on your network?  Does the login page appear?

**Comment by Akszyn** [comment]
no

**Comment by DesktopECHO** [comment]
> I can't access from any device on my network whether it's via pc or smartphone and I have a 404 message that the page on exists

What is the full URL the you are trying to access the admin page from?

> And besides, on the device where the application is installed, there is a message to update pihole in admin page

Login to the container via SSH or RDP and run `pihole -up` to fully update Pi-hole.

**Comment by Akszyn** [comment]
In the application settings I changed the password and I still can not log in it via ssh so how can I do it otherwise?

**Comment by DesktopECHO** [comment]
When you change the password you need to run "Apply Configuration" to send that change to the container.

![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/5c218eb8-e63e-4f29-951a-f2ada7bb3b2f)

**Comment by Akszyn** [comment]
I do not see this option even though I restarted the application and the phone is the password in the settings is what I set but the ssh screams that it is wrong and besides, is it possible to block ads everywhere (outside the local network), even on the go with the help of some Wireguard VPN?

**Comment by DesktopECHO** [comment]
> I do not see this option

If you don't see it, what is it that you actualy see?

**Comment by Akszyn** [comment]
There is a translation error because instead Apply Configuration is Configuration Again on Polish language and as for the VPN issue, how does this adblock look like on the mobile network outside the local network ?

**Comment by DesktopECHO** [comment]
> for the VPN issue, how does this adblock look like on the mobile network outside the local network ?

Unfortunately I can't say for sure --  have not done any testing over VPN's, and mobile networks can have differences in behaviour depending on the operator.
I can only suggest you experiment with it and see if you can get the result you're looking for.
