### ISSUE TITLE
TLS error when initial download

### ISSUE THREAD

**Issue by nikhilk0** [DesktopECHO/Pi-hole-for-Android#68]
Getting below error when initial image download is being attempted. 

![Screenshot_20230826-152112095.jpg](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/45728234/78c52680-529d-466c-af4c-916197ee8c7d)

Tried multiple networks. 

Not sure if there is any way to manually deploy the image.

**Comment by dhruvhaldar** [comment]
same error, can't install `ca-certificates`

**Comment by DesktopECHO** [comment]
What is the make, model and Android version of your device?
I'm unable to replicate the issue on one of my test devices.

![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/697b3172-8e8b-4bec-9e64-74c8540b98f9)

**Comment by nikhilk0** [comment]
I'm using Redmi 4 running PE 10 rom. Will try again with VPN later today.

**Comment by DesktopECHO** [comment]
You can also download the Debian image via web browser,  then in settings specify the filesystem location rather than a http://... URL
