### ISSUE TITLE
Mistake in install documentation

### ISSUE THREAD

**Issue by code-r-man** [DesktopECHO/Pi-hole-for-Android#69]
Current readme file states that the user should select "Install" under three dots menu. It should really say "New Deployment".

**Comment by DesktopECHO** [comment]
Thanks Nikola, this was carraied over from an older version of the APK.  Now fixed.

<img width="1088" alt="image" src="https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/9f0a6e96-dc7f-4b11-9967-8aac716a41bb">
