### ISSUE TITLE
Temp sensor not found

### ISSUE THREAD

**Issue by SpidaXS** [DesktopECHO/Pi-hole-for-Android#7]
Hello, i got the pi hole to run however on the dashboard it saids “temp sensor not found”. Also I see a message saying the pi hole is out of date. How can I update this? When I try to I get an error. Thank you

**Comment by SpidaXS** [comment]
Also when I run dnslesktest it points to woodynet? I see it is a server from quad9 but I didn’t choose quad9 in pihole?

**Comment by DesktopECHO** [comment]
Temp sensor and incorrect message to update are both bugs that will be fixed upstream in the next version.
The default setup for DNS lookups is to use Unbound which is preinstalled.  
It is configured to use DoT and listens on localhost port 5335.
(See ``/etc/unbound/conf.d/pihole.conf``)

**Comment by SpidaXS** [comment]
Thank you, do you know how to get dhcp in pihole working? I’ve set a static ip for my android and disabled dhcp on my router however when I enable dhcp in pi hole my devices still cannot connect

**Comment by SpidaXS** [comment]
ive disabled dhcp on pihole for now and enabled it back on my router just so my home devices can connect to wifi again sadly that means ill have to troubleshoot at night. anyways in padd i also get the error "/bin/padd: line 264: [: -gt: unary operator expected" at the bottom. 
![Capture](https://user-images.githubusercontent.com/99109882/152699144-866b22a9-a691-4041-8c48-e6a94bea753c.PNG)

**Comment by DesktopECHO** [comment]
To update padd run:

``wget -N https://raw.githubusercontent.com/pi-hole/PADD/master/padd.sh -O /bin/padd``

Not sure what's up with DHCP in your setup.  I just tested Pi-Hole DHCP on a Moto G7 Play without issue.
 
![Untitled](https://user-images.githubusercontent.com/33142753/152720451-c681a857-cacb-4aa3-9c6f-6b335c49154a.png)

**Comment by SpidaXS** [comment]
thank you, i will try to play around with dhcp tonight. about the padd- it is already the latest version and ive tried updating it and it still displays that. also still gettiing error "/bin/padd: line 264: [: -gt: unary operator expected"

**Comment by DesktopECHO** [comment]
Looking at the code, it's something to do with the temperature monitoring.   But it's strange that PADD is working on other devices I have here... anyway you can try to get past this by editing ``/bin/padd`` and commenting out the offending code like so:
![image](https://user-images.githubusercontent.com/33142753/152728771-ef20c5c3-1eb3-4c5c-8931-03bf94aa4132.png)
If anyone else can re-create this issue I'll file a bug report upstream.  Right now not sure if this is a real issue with other devices or a one-off problem.

**Comment by SpidaXS** [comment]
thanks, it is definitely strange. could it be my android version or phone? i was on arrowos 11 vanilla before and now i am trying on lineage os 18.1. ii am also on google pixel 2

**Comment by DesktopECHO** [comment]
I doubt it's the Android version but we'll keep assembling evidence until something makes sense.
I opened an issue for PADD not showing as up to date.  https://github.com/pi-hole/PADD/issues/192

**Comment by DesktopECHO** [comment]
Also... if you don't mind trashing and re-deploying the image you can try
``pihole checkout dev``
...as an experiment to see if any of your issues are solved in the latest developer snapshot

**Comment by SpidaXS** [comment]
hello thank you. ive ran "pihole checkout dev" and the upgrade completed successfully. now on the dashboard the temperature message is gone however no temperature displays at all. as for the padd issue - not only am i getting "/bin/padd: line 264: [: -gt: unary operator expected" i am also getting "piHoleVersion: line 6: syntax error near unexpected token `('
piHoleVersion: line 6: `web_version_latest=(:'
piHoleVersion: line 9: unexpected EOF while looking for matching `)'". as for dhcp, i still havent figured it out

**Comment by SpidaXS** [comment]
![Capture2](https://user-images.githubusercontent.com/99109882/152866694-f0ec78cd-c60e-4e65-89d8-e5155da0470d.PNG)
![Capture3](https://user-images.githubusercontent.com/99109882/152866703-30ff8c53-d8cc-4fb8-9652-60cab81f117d.PNG)

**Comment by SpidaXS** [comment]
can dhcp not working be my android wifi settings? i have set a static ip "192.168.2.80" network prefix length to 24 and dns to local host 127.0.0.1 and private dns is off.  i have also updated to android 12

**Comment by SpidaXS** [comment]
Could this be an issue with my modem/router? I think it is not related to this image. I am with the bell service in canada and have also seen some people with trouble. I see you are also in canada!

**Comment by DesktopECHO** [comment]
Not quite, I work in Bermuda currently, but born and raised in the maritimes. :)

Can you tell your router to use Pi-hole for DNS, and leave DHCP to the router?  That will work around your DHCP challenges nicely.  

You can also try the ARMv8 Image I linked to in another thread, but I don't think this will work any better in this situation.

**Comment by SpidaXS** [comment]
> Not quite, I work in Bermuda currently, but born and raised in the maritimes. :)
> 
> Can you tell your router to use Pi-hole for DNS, and leave DHCP to the router? That will work around your DHCP challenges nicely.
> 
> You can also try the ARMv8 Image I linked to in another thread, but I don't think this will work any better in this situation.

nope.. sadly bell does not allow the use to local dns for residential customers.. i have seen people get it working before by disabling dhcp. also i have tried the armv8 image but whenever i use that the ftl server is disabled on that image

**Comment by SpidaXS** [comment]
well i will close the issue since it is fixed, thank you so much. also if i update the pihole or padd i will need to re run the command right?

**Comment by DesktopECHO** [comment]
Yes.  Actually you can edit ``/etc/rc.local`` and comment out the line that automatically downloads PADD at startup.
That way you won't have to mess with it again.

**Comment by Dynasty-Dev** [comment]
> Yes. Actually you can edit `/etc/rc.local` and comment out the line that automatically downloads PADD at startup. That way you won't have to mess with it again.

thank you! very useful, wont be updating pihole much. also for linuxdeploy i think it iis just old, im not sure how to use Dropbear  or disable pirvelage seperation. i can just use telnet in settings right?

**Comment by DesktopECHO** [comment]
Only if you trust the network you're on.  Telnet doesn't have any security layers so it's not recommended to leave on all the time unless you know what you're doing.  Or just leave telnet off and RDP into the device instead.

**Comment by Dynasty-Dev** [comment]
> Only if you trust the network you're on. Telnet doesn't have any security layers so it's not recommended to leave on all the time unless you know what you're doing. Or just leave telnet off and RDP into the device instead.

Ok, thank you.

**Comment by Dynasty-Dev** [comment]
> Only if you trust the network you're on. Telnet doesn't have any security layers so it's not recommended to leave on all the time unless you know what you're doing. Or just leave telnet off and RDP into the device instead.

Well I don’t know how you got it working but ssh and Vnc don’t work in Debian and other distributions for me. Only works in centos

**Comment by Dynasty-Dev** [comment]
Also DHCP update, I ended up trying pihole on my laptop running Ubuntu and DHCP worked. Also I recently bought a pi zero and DHCP worked. It is probably an issue with my android phone then.
