### ISSUE TITLE
install Pihole on an SD card

### ISSUE THREAD

**Issue by SonThanhVN** [DesktopECHO/Pi-hole-for-Android#71]
is there any way to make pihole use the whole 32GB SDcard ?

**Comment by DesktopECHO** [comment]
If the SD card is formatted EXT3/4, you can change the location of where the Linix Container's root is located to the SD card.  Or you can try installing to an image file on the SD card.  Information about where the SD card's mountpoint is will vary by model, so I can't offer much more advice past that.
