### ISSUE TITLE
wget: note: TLS certificate validation not implemented

### ISSUE THREAD

**Issue by BR-lovecraft** [DesktopECHO/Pi-hole-for-Android#73]
Dont installing

**Comment by DesktopECHO** [comment]
It's a warning, not an error.  
Give it a few minutes to download the image and the installer should continue.

**Comment by null2264** [comment]
It actually causes an error for me instead of just warning,

```
wget: tls error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```

I ended up uploading the raspbian image to my CDN server and changed the URL in the deploy setting to my CDN URL... Probably just GitHub rejecting the request or something.
