### ISSUE TITLE
New Deployment Error

### ISSUE THREAD

**Issue by AshokShk** [DesktopECHO/Pi-hole-for-Android#74]
>>> deploy
## bootstrap/rootfs : do_install && do_configure
:: Installing bootstrap/rootfs ... 
Checking installation path ... done
Checking file system ... skip
Mounting the container: 
/ ... done
/proc ... done
/sys ... done
/dev ... done
/dev/shm ... done
/dev/pts ... done
Download in progress, one moment ···
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
fail
<<< deploy

**Comment by DesktopECHO** [comment]
Hi, what is the make and model of your device?
Deployed image to a 2017 Kindle Fire HD8 just a few minutes ago, no problems.

![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/45b06172-614a-4771-9402-152aaf35289f)

**Comment by AshokShk** [comment]
Oneplus 8T KB2001

**Comment by AshokShk** [comment]
Resolved Thankyou

**Comment by CutterSol** [comment]
This worked for me too.  Running LineageOS 17.1, I believe..  On a Nexus 5x.  

Initially I thought you might have to have SU installed, and Magisk would not work, partly because I was trying the curl command from Pi-hole to install...  Going to give NextCloud a shot next...
