### ISSUE TITLE
Not able to download the raspian.tgz image fro Github

### ISSUE THREAD

**Issue by driftywinds** [DesktopECHO/Pi-hole-for-Android#77]
The error I repeatedly get is `wget: error getting response: Connection reset by peer fail` regardless of trying out VPNs and proxies to get it to connect. The issue is not on my side for sure, what could I do to make it work?

**Comment by DesktopECHO** [comment]
If you can, try a different WiFi network.  

You can also download the file using the web browser installed on the device.  When the image is downloaded, open Pi Deploy and tap Properties.  Change the _Source path_ from:

`https://github.com/DesktopECHO/Pi-hole-for-Android/releases/latest/download/raspbian.tgz`

..to the location of the downloaded file (exact path may vary by device):

`/sdcard/Download/raspbian.tgz `

**Comment by driftywinds** [comment]
Thank you this fixed it!

**Comment by Tobi828282** [comment]
Hi,
my problem seems to be a read only filesystem. How can  change that?
Message when trying to install:
>>> deploy
## bootstrap/rootfs : do_install && do_configure
:: Installing bootstrap/rootfs ... 
Checking installation path ... done
chmod: ./raspbian: Read-only file system
chmod: ./raspbian: Read-only file system
rm: can't remove './raspbian': Read-only file system
Checking file system ... skip
Mounting the container: 
/ ... mount: mounting ./raspbian on /data/local/raspbian failed: Invalid argument
fail
<<< deploy

Thanks in advance for your help!
