### ISSUE TITLE
Failed to create Client object: dameon not running 

### ISSUE THREAD

**Issue by Ugotmo** [DesktopECHO/Pi-hole-for-Android#81]
Updated to newest version. 
New deployment 

Start and get the error 
![Screenshot_20240104-135557_Pi Deploy](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/46436473/66713708-0afd-4d48-9be7-0897e2f50777)

**Comment by DesktopECHO** [comment]
This is `avahi-publish` complaining because some other service is likely handling Zeroconf on your device.  

It should not affect the operation of Pi-hole.  Do you have any issues other than the `Daemon not running` message?

**Comment by Ugotmo** [comment]
0 active clients

**Comment by Ugotmo** [comment]
![Uploading Screenshot_20240104-141747_Cromite.png…]()

**Comment by Ugotmo** [comment]
![Screenshot_20240104-141747_Cromite](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/46436473/879604a0-6ed1-4685-9d69-c39921563100)

**Comment by DesktopECHO** [comment]
Did you point your clients DNS to the IP of the Pi-hole?

**Comment by Ugotmo** [comment]
No. I knew it was something easy.  I'm not sure how.  Can you point me to the correct documentation. 

Thanks for the help

**Comment by DesktopECHO** [comment]
https://docs.pi-hole.net/

Try method 3 and configure a couple of clients manually to try out Pi-Hole:

https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server

**Comment by Ugotmo** [comment]
Looks like drop bear failed to start

Jan 4, 2024 2:13:11 PM DesktopECHO ***@***.***>:
