### ISSUE TITLE
Read only file system

### ISSUE THREAD

**Issue by Tobi828282** [DesktopECHO/Pi-hole-for-Android#82]
Hi,
my problem seems to be a read only filesystem. How can change that?
Message when trying to install:

```
>>> deploy
## bootstrap/rootfs : do_install && do_configure
:: Installing bootstrap/rootfs ... 
Checking installation path ... done
chmod: ./raspbian: Read-only file system
chmod: ./raspbian: Read-only file system
rm: can't remove './raspbian': Read-only file system
Checking file system ... skip
Mounting the container: 
/ ... mount: mounting ./raspbian on /data/local/raspbian failed: Invalid argument
fail
<<< deploy
```

Thanks in advance for your help!

**Comment by DesktopECHO** [comment]
What is the make and model of your device?

You can try installing to an image file instead of directory.  
Open **Properties** and for **Installation Type** select **_File_**
Re-deploy and see if the error is still present.

**Comment by Tobi828282** [comment]
Thank you very much for your response. 
The device is a Oneolus One running lineage os 14.

Only installing to RAM worked on the device. This is no problem for me since the phone is operating 24/7.

**Comment by DesktopECHO** [comment]
If that solution works for you that's great and we can close the issue.  

If not, you may need to disable SElinux with this [Magisk module](https://github.com/evdenis/selinux_permissive) or install [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger) then set SELinux to _Permissive_ or _Disabled_.  

If SELinux is out of the way and you **still** have issues, try changing the install target (Default is ```./rasbian```) to ```/data/local/raspbian-root```

**Comment by Tobi828282** [comment]
Now I installed it to /data/local/raspbian-root and it seems to work fine. 
Thank you very much for your help!
