### ISSUE TITLE
New Deployment Error - Installation stop

### ISSUE THREAD

**Issue by sandfield14** [DesktopECHO/Pi-hole-for-Android#83]
Hi I'm trying to install pi-hole on a myGica ATV 1900 Pro.
I reseted the unit to factory default and root it. 

After installing the Linux environment and hitting new development I get the error: 

<stdin>[4]: /data/data/com.desktopecho.pideploy/files/bin/pideploy: no such files or directory

I did check and all the files are there. 
I also tried a few older version but I got the same message. 
![IMG_1723](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/156609433/a73ab331-2336-47b7-ad2c-43d38d4ee1d6)

**Comment by DesktopECHO** [comment]
What is the make/model of your device?
Is your device rooted?

Uninstall the APK, reboot, and re-install the APK.  Do you get a toast (pop-up) message saying root was activated when you start a new deployment?

**Comment by sandfield14** [comment]
Thanks for your reply, I did what you ask and got the toast but I still get the same error. 
I'm rooted for sure.

**Comment by sandfield14** [comment]
When I restarted the program I got the error: 
<stdin>[2]: busybox: No such file or directory

**Comment by sandfield14** [comment]
Using myGica ATV 1900 Pro

**Comment by sandfield14** [comment]
running 5.1 Lolipop

**Comment by DesktopECHO** [comment]
That’s a fairly old device, did you deploy the 32-bit image?

**Comment by sandfield14** [comment]
No I did not try, the image worked fine on an other unit that I have (MINIX NEO 7 Lollipop as well).
It does reach the image step, the error message comes before. 
The path is good.

**Comment by sandfield14** [comment]
For some reasons it can not find the the correct path to find the "deploy" file. 
Busybox is also in there and it's not found as well.

**Comment by DesktopECHO** [comment]
For Android 5.1 devices you need to use the 32-bit image.

**Comment by sandfield14** [comment]
I tried and got the same behavior. 
thanks for your help
