### ISSUE TITLE
Unable to install PIXEL Desktop

### ISSUE THREAD

**Issue by Fat-ctrl** [DesktopECHO/Pi-hole-for-Android#85]
Hi, I'm encountering an issue with PIXEL Desktop installation on Pi-hole for Android.

After deploying Pi-hole and running `pideploy-gui-install`, I received an error:
![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/67115065/55287aa7-083d-4c12-a622-dcf1869ab027)

When I log in via RDP, I only see an enlarged terminal, not the full desktop:
![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/67115065/5d16f906-ab41-4416-a732-5c001db1869e)

I've successfully installed the desktop on the same device/app before, but now I'm encountering this error.

I also tried installing libfm-gtk4, running `sudo apt update`/`sudo apt autoremove`, redeploy the image, reinstall the app, and changing the Wi-Fi network, but none of it worked.

I'd appreciate any assistance in resolving this issue.

**Comment by DesktopECHO** [comment]
Looks like a problem upstream ->  https://github.com/raspberrypi/bookworm-feedback/issues/203

Now that it's been fixed, try re-running `pideploy-gui-install` and you should be good to go.

**Comment by Fat-ctrl** [comment]
> Looks like a problem upstream -> [raspberrypi/bookworm-feedback#203](https://github.com/raspberrypi/bookworm-feedback/issues/203)
> 
> Now that it's been fixed you can either just redeploy the image, or re-run `pideploy-gui-install` and you should be good to go.

Yes, the problem is fixed now, thanks for the reply
