### ISSUE TITLE
Start Pi-hole automatically

### ISSUE THREAD

**Issue by alexfernandez** [DesktopECHO/Pi-hole-for-Android#87]
Thanks a lot for your work.

I have purchased a [Firefly Station M2](https://en.t-firefly.com/product/industry/stationm2) which is a little nifty ARM computer, with the intention of setting up a PiHole on it. Since it comes preloaded with Android I want to use your awesome package, and it runs pefectly out of the box. But I would very much prefer to set it up as a headless system; therefore I would need Pi-hole to start automatically in case the device is rebooted.

I have not even managed to start Pi-hole-for-Android using the `adb shell` command line. Can I somehow coerce the Raspbian system to start on startup, and then run start the Pi-hole automatically? Any progress would be welcome, such as creating an activity that starts the Pi-hole.

Thanks in advance!

**Comment by DesktopECHO** [comment]
Hi, have a look in the settings menu -- There's an option to run Pi Deploy at startup:

![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/33142753/40e356c3-233f-4238-8708-9a3715a30e86)

**Comment by alexfernandez** [comment]
Oh, thanks! That's really useful. Does it also start the Pi-hole automatically when the app starts?

**Comment by DesktopECHO** [comment]
Yes, all background services are started as well.

**Comment by alexfernandez** [comment]
Awesome, thanks a bunch :muscle: Great job with the project  :heart:
