### ISSUE TITLE
hostname change

### ISSUE THREAD

**Issue by dreaddymck** [DesktopECHO/Pi-hole-for-Android#88]
How do I change hostname? Modifying the hosts/hostname files after installation breaks ssh login.

**Comment by DesktopECHO** [comment]
You'l need to change this in the `````android-raspbian````` initscript

`````
sudo nano +32 /etc/init.d/android-raspbian
`````

Change
`````
hostname=$(unchroot getprop ro.product.device)
`````
to
`````
hostname="mydevicename"
`````

**Comment by dreaddymck** [comment]
Thanks but this solution break ssh as well. 

I can see dropbear failed when I reload also removing the changes will not fix it. 

I have the busybox app installed as well, could that be the problem?

**Comment by DesktopECHO** [comment]
Just redeploy a clean container to verify SSH works out-of-the-box.
If it does, login and change the hostname with `````/etc/init.d/android-raspbian````` per my earlier commoent.
Changing the host this way shouldn't affect Dropbear's ability to start.

**Comment by dreaddymck** [comment]
You may be right, I think something unrelated is breaking dropbear and requires further investigation.

I think your suggestion is the correct answer so I will close the issue. 

Thank you

**Comment by dreaddymck** [comment]
The device is 32 bit and problem was `/raspbian.tgz` was installed instead of `/raspbian32.tgz`.
