### ISSUE TITLE
PADD not working

### ISSUE THREAD

**Issue by Dynasty-Dev** [DesktopECHO/Pi-hole-for-Android#9]
Hello,  I successfully installed pihole on my android device all thanks to you. I sshed to my android device on windows using putty but when I type the "padd" nothing happens.

**Comment by Dynasty-Dev** [comment]
Also thank you for getting this to work I dont know how you did as i tried doing it manually using debian and ubuntu but linuxdeploy would not start ssh

**Comment by ashishkotnala29** [comment]
You need to change SSH port to something other than 22 for other distributions. Try 2222 in Linux deploy settings.
As for padd not working, make sure you are connected to the internet on your device when you run the container for the first time, it updates padd.

**Comment by Dynasty-Dev** [comment]
> You need to change SSH port to something other than 22 for other distributions. Try 2222 in Linux deploy settings. As for padd not working, make sure you are connected to the internet on your device when you run the container for the first time, it updates padd.

Hello! Thanks, Ive tried my own installation on debian using 2222 and other ports with no success. Also i tried running the installation multiple times with wifi and it didnt install padd. but thanks for suggesting to run the update padd command, i found the update padd command and it works now. Only problem is the temperature shows no sensor found on the pihole dashboard and padd. Padd also displays a few error related to temperature

**Comment by ashishkotnala29** [comment]
being discussed here: https://github.com/DesktopECHO/Pi-hole-for-Android/issues/7

**Comment by DesktopECHO** [comment]
> Hello! Thanks, Ive tried my own installation on debian using 2222 and other ports with no success. 

Use Dropbear SSHd instead of OpenSSH.  
Or disable privilege separation in ``sshd_config``

Regarding the temp sensor, if the sensor can't be read by Pi-hole, the old behaviour was to warn you there's no temp sensor.  In the next Pi-hole update, it will just skip it altogether and not display temp info on the web page.  Pi-hole can read the temp sensors of some devices, others not.  Pi-hole works fine otherwise.

Can you send a screenshot of your PADD issues relating to temeratures?

**Comment by Dynasty-Dev** [comment]
> > Hello! Thanks, Ive tried my own installation on debian using 2222 and other ports with no success.
> 
> Use Dropbear SSHd instead of OpenSSH. Or disable privilege separation in `sshd_config`
> 
> Regarding the temp sensor, if the sensor can't be read by Pi-hole, the old behavior was to warn you there's no temp sensor. In the next Pi-hole update, it will just skip it altogether and not display temp info on the web page. Pi-hole can read the temp sensors of some devices, others not. Pi-hole works fine otherwise.
> 
> Can you send a screenshot of your PADD issues relating to temperatures?

Thank you for the solution, good to know it will be removed soon but its unfortunate I won't be able to see the temperature of my device. 
![Putty](https://user-images.githubusercontent.com/89283708/153088013-df4e9c7f-4160-4692-be77-84220e79db9a.jpg)

**Comment by DesktopECHO** [comment]
What is the output of:
``cat /sys/class/thermal/thermal_zone0/temp``

**Comment by SpidaXS** [comment]
cat: /sys/class/thermal/thermal_zone0/temp: Input/output error

**Comment by DesktopECHO** [comment]
Your phone doesn't report temperatures in the 'usual' place.

How about:
``cat /sys/class/hwmon/hwmon0/temp1_input``
If that doesn't return a value like 32125 or similar, what is the output of:
``grep . /sys/class/thermal/*/*``

**Comment by SpidaXS** [comment]
> Your phone doesn't report temperatures in the 'usual' place.
> 
> How about: `cat /sys/class/hwmon/hwmon0/temp1_input` If that doesn't return a value like 32125 or similar, what is the output of: `grep . /sys/class/thermal/*/*`

Hey, got an output of "29500" by running cat /sys/class/hwmon/hwmon0/temp1_input

**Comment by Dynasty-Dev** [comment]
> What is the output of: `cat /sys/class/thermal/thermal_zone0/temp`
got an input error, with cat /sys/class/hwmon/hwmon0/temp1_input I get a value returned

**Comment by DesktopECHO** [comment]
Patch PADD with this command, then see if it works:

``sudo sed -i 's#/sys/class/thermal/thermal_zone0/temp#/sys/class/hwmon/hwmon0/temp1_input#g' /bin/padd``

**Comment by Dynasty-Dev** [comment]
> Patch PADD with this command, then see if it works:
> 
> `sudo sed -i 's#/sys/class/thermal/thermal_zone0/temp#/sys/class/hwmon/hwmon0/temp1_input#g' /bin/padd`

Wow, I can see temps fine now! Thank you! Could this somehow be implemented on the pihole dashboard too?
![Temp](https://user-images.githubusercontent.com/89283708/153092131-90dc181e-b398-43b6-93bf-90063297f55b.jpg)

**Comment by DesktopECHO** [comment]
Maybe.  Try this one-liner and reload the web page:
``sudo sed -i 's#/sys/class/thermal/thermal_zone0/temp#/sys/class/hwmon/hwmon0/temp1_input#g' /var/www/html/admin/scripts/pi-hole/php/header.php``

**Comment by SpidaXS** [comment]
> > Patch PADD with this command, then see if it works:
> > `sudo sed -i 's#/sys/class/thermal/thermal_zone0/temp#/sys/class/hwmon/hwmon0/temp1_input#g' /bin/padd`
> 
> Wow, I can see temps fine now! Thank you! Could this somehow be implemented on the pihole dashboard too? ![Temp](https://user-images.githubusercontent.com/89283708/153092131-90dc181e-b398-43b6-93bf-90063297f55b.jpg)

temperature is working now! thank you a lot! <3

**Comment by DesktopECHO** [comment]
Fixed upstream thanks @Blumlaut for researching the 'right' way to check temp sensors.
