### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [DesktopECHO/Pi-hole-for-Android#91]
Hello, would you please consider publishing the app on F-Droid ?
Also, what's the license of this project ?

**Comment by DesktopECHO** [comment]
Hello,

The license is the same (GPL3) as Linux Deploy, from which this forked.
I've not used F-Droid before but I'll look into what's required for publishing.

**Comment by shuvashish76** [comment]
> The license is the same (GPL3) as Linux Deploy, from which this forked.

Yes I noticed it but nothing mentioned as such here. The license file has to be put in root directory or the project.

Requested for packaging : https://gitlab.com/fdroid/rfp/-/issues/2714

**Comment by DesktopECHO** [comment]
Hi, "Pi hole for Android" is made up of two parts, the Android APK and the Raspbian disk image that's downloaded when an instance is created.  This repo is for the disk image part, and the repo for the APK source code is here:
[https://github.com/DesktopECHO/pideploy](https://github.com/DesktopECHO/pideploy)

**Comment by DesktopECHO** [comment]
Found [this](https://gitlab.com/fdroid/rfp/-/issues/2105) issue filed for Linux Deploy.
We would have the same challenges as the last time LD was submitted and I'm not terribly interested in the extra work required to get this in their app store, sorry.

**Comment by licaon-kter** [comment]
@DesktopECHO which challenge exactly?
