### ISSUE TITLE
Failed to create client object: Daemon not running

### ISSUE THREAD

**Issue by vavavr00m** [DesktopECHO/Pi-hole-for-Android#93]
As the title says, not sure what I'm doing wrong. This is my first time. Do note:
1. Dropbear (app log): "fails"
2. VNC (app log): "The X session exited with status 127! Killing Xtigertvnc process ID 29839".
3. Pi-hole diagnosis (pi-hole log): "Long-term load (15min avg) larger than number of processors: 28.0 > 8
This may slow down DNS resolution and can cause bottlenecks."

To test, I added the everything list from [the Blocklist Project](https://github.com/blocklistproject/lists/), updated gravity, changed my phone's wifi connection's dns addresses to both pi-hole's and tried visiting https://nyaa.si using Chrome for Android and nyaa still loaded. Certain the domains were added, however, no clients are connected to the pi-hole. While I'm able to connect to the dashboard on a PC, the filtering doesn't seem to be properly working for me.

Let me know if you need anything else.

**Comment by DesktopECHO** [comment]
Hi, what is the make and model of your device?

**Comment by DesktopECHO** [comment]
This issue is not specific to Pi-hole running on Android.  See here for some other ideas on how to troubleshoot:
https://www.reddit.com/r/pihole/comments/qr1txw/at_a_loss_about_android_chrome_not_using_pihole/

**Comment by DesktopECHO** [comment]
Are you able to RDP into the instance instead of SSH?   
If so, you can edit Dropbear's configuration file to use a different port. 

The high load average is normal to see on some Android devices and is only a cosmetic issue, see here:  https://github.com/DesktopECHO/Pi-hole-for-Android/issues/84

**Comment by DesktopECHO** [comment]
Agree... Uninstall the APK, reboot, re-install and create a New Deployment.  It should give you a new password.

If you still have issues try the 32-bit image to see if that behaves any differently.

**Comment by DesktopECHO** [comment]
I don't understand why VNC is trying to start, that's not even enabled or configured in the installer.

None of the 'errors' you mention is a security problem.  

Regarding the container being killed, Google for "prevent oom killer android".  None of my lab devices have this problem but it could be an issue with some devices.
