### ISSUE TITLE
Unable to Login into RDP after Running PiDeploy-gui-install

### ISSUE THREAD

**Issue by AkashPanja** [DesktopECHO/Pi-hole-for-Android#94]
After Runing pideploy-gui-install unable to login through RDP, it is getting started and after few seconds getting closed with only black screen.

as of now SSH is working, is there any way to disable gui.

**Comment by AkashPanja** [comment]
I tried to reinstall got this

**Comment by AkashPanja** [comment]
> How do you even install it? I am unable to type

If you login through RDP, a terminal will be visible also you can use ssh android@localdeviceip
Then enter the password which was visible at first time run.

**Comment by DesktopECHO** [comment]
> I tried to reinstall got this 

Hi... See here for info to update the Pixel Desktop installer: https://github.com/DesktopECHO/Pi-hole-for-Android/issues/58#issuecomment-1563526025

**Comment by AkashPanja** [comment]
It did not work, I will try it on fresh install later, anyway thanks a lot.
