### ISSUE TITLE
Cant Run programms in terminal

### ISSUE THREAD

**Issue by Asmod4n** [DesktopECHO/Pi-hole-for-Android#95]
When trying to Run pihole, sudo or apt from the terminal i Just get command Not found. I also cant access the raspbian/bin folder because i dont have permissions to do so.

How is one expected to use IT on the Tablet ?

**Comment by DesktopECHO** [comment]
You need to SSH into the Pi-hole instance, either from another computer on your home network, or by installing an SSH client on your device.

**Comment by Asmod4n** [comment]
So it’s not Enough to use the built in terminal? Cant that be fixed?

**Comment by DesktopECHO** [comment]
See if you can call the the binary directly:
`/data/data/com.desktopecho.pideploy/bin/pideploy shell`
