### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AbdurRoufBusiness** [DesktopECHO/Pi-hole-for-Android#97]
Phone rooted with magisk 
![image](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/132583428/08f116ee-c454-4a64-8543-92373a313cae)

**Comment by DesktopECHO** [comment]
What is the make/model of the device? 
If it's Samsung, you probably need to use a DeKnox'ed ROM like LineageOS.

You may need to use the 32-bit image instead of the default 64-bit image, or you may need to disable selinux.

**Comment by AbdurRoufBusiness** [comment]
I am using galaxy s8 dreamlte which is a exynos model .. i am using a custom kernel called a2n kernel . And yes selinux is disabled in this kernal ,, unfortunately i cant install lineageos as the phone doesn’t have a display and i use it with dex mode with a hdmi hub and its a armv8a system so i deployed the defolt rasbian image

**Comment by DesktopECHO** [comment]
Did you try the 32-bit version of the image?  
If that doesn't work and you can't install LineageOS, I don't think it will work.

**Comment by AbdurRoufBusiness** [comment]
Ok i can try the 32 bit one ,, will let you know if it works or not
