### ISSUE TITLE
Possibilities of having homebridge or openhab 

### ISSUE THREAD

**Issue by AbdurRoufBusiness** [DesktopECHO/Pi-hole-for-Android#98]
Hello developer ,, i was thinking if we can run a openhab or homebridge server on this image .. i have tried to install java 17 but got dpkg error,, tried to install homebridge but the ui isn’t running,,
Using a arm32 device now specifically galaxy s4 
Do you have any suggestions 

edit
In homebridge installation there’s apache server error I think that’s why it’s not working

**Comment by DesktopECHO** [comment]
HomeBridge should work fine but I can't assist without more information.

**Comment by AbdurRoufBusiness** [comment]
![IMG_2089](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/132583428/ba000d5a-014d-4ead-b1dc-4206ffdb10e3)
Didn’t work

**Comment by DesktopECHO** [comment]
Try this:
`dpkg --purge --force-all postfix ; apt-get -y install postfix`
