### ISSUE TITLE
Tried to install nextcloud 27 got dpkg error 

### ISSUE THREAD

**Issue by AbdurRoufBusiness** [DesktopECHO/Pi-hole-for-Android#99]
cess returned error exit status 1
Errors were encountered while processing:
 postfix
E: Sub-process /usr/bin/dpkg returned an error code (1)

Amr32 
Galaxy s4 device with lineagos android 10
Run the installation command as a non root user 

got this error while installing java 17 as well

**Comment by DesktopECHO** [comment]
What steps did you take to install Java 17?  Was it the JRE or JDK?

**Comment by AbdurRoufBusiness** [comment]
Used this command < sudo apt install openjdk-17-jdk >

**Comment by DesktopECHO** [comment]
Run this first then try re-installing openjdk-17-jdk:

`mkdir -p /usr/share/man/man1/`
